/** Palabras clave según su papel en el subconjunto SELECT v1 (LAB_SPEC). */

/** Construcciones válidas en Oracle que pertenecen a unidades futuras. */
export const FUTURE_KEYWORDS: ReadonlyMap<string, string> = new Map([
  ['WHERE', 'Filtrar filas con WHERE'],
  ['ORDER', 'Ordenar filas con ORDER BY'],
  ['GROUP', 'Agrupar con GROUP BY'],
  ['HAVING', 'Filtrar grupos con HAVING'],
  ['JOIN', 'Combinar tablas con JOIN'],
  ['INNER', 'Combinar tablas con JOIN'],
  ['LEFT', 'Combinar tablas con JOIN'],
  ['RIGHT', 'Combinar tablas con JOIN'],
  ['FULL', 'Combinar tablas con JOIN'],
  ['CROSS', 'Combinar tablas con JOIN'],
  ['NATURAL', 'Combinar tablas con JOIN'],
  ['ON', 'Combinar tablas con JOIN'],
  ['UNION', 'Combinar consultas con UNION'],
  ['INTERSECT', 'Combinar consultas con INTERSECT'],
  ['MINUS', 'Combinar consultas con MINUS'],
  ['EXCEPT', 'Combinar consultas con EXCEPT'],
  ['WITH', 'Subconsultas con WITH'],
  ['CASE', 'Expresiones condicionales con CASE'],
  ['LIKE', 'Comparar patrones con LIKE'],
  ['BETWEEN', 'Comparar rangos con BETWEEN'],
  ['IN', 'Comparar listas con IN'],
  ['IS', 'Trabajar con NULL'],
  ['NULL', 'Trabajar con NULL'],
  ['AND', 'Combinar condiciones con AND, OR y NOT'],
  ['OR', 'Combinar condiciones con AND, OR y NOT'],
  ['NOT', 'Combinar condiciones con AND, OR y NOT'],
  ['FETCH', 'Limitar filas con FETCH'],
  ['OFFSET', 'Limitar filas con OFFSET'],
  ['CONNECT', 'Consultas jerárquicas'],
  ['START', 'Consultas jerárquicas'],
  ['FOR', 'Bloquear filas con FOR UPDATE'],
  ['UNIQUE', 'Usa DISTINCT en esta unidad'],
  ['ALL', 'La palabra ALL'],
  ['ROWNUM', 'Pseudocolumnas como ROWNUM'],
  ['ROWID', 'Pseudocolumnas como ROWID'],
  ['LEVEL', 'Pseudocolumnas como LEVEL'],
  ['SYSDATE', 'Fechas del sistema como SYSDATE'],
  ['DUAL', 'La tabla especial DUAL'],
]);

/** Sentencias que modifican datos, estructura o permisos: nunca llegan al motor. */
export const FORBIDDEN_STATEMENTS = new Set([
  'INSERT',
  'UPDATE',
  'DELETE',
  'MERGE',
  'UPSERT',
  'DROP',
  'CREATE',
  'ALTER',
  'TRUNCATE',
  'RENAME',
  'GRANT',
  'REVOKE',
  'BEGIN',
  'DECLARE',
  'EXEC',
  'EXECUTE',
  'CALL',
  'COMMIT',
  'ROLLBACK',
  'SAVEPOINT',
  'LOCK',
  'SET',
]);

/** Palabras que cierran la lista de SELECT: no pueden leerse como alias implícito. */
export const CLAUSE_KEYWORDS = new Set([
  'SELECT',
  'DISTINCT',
  'FROM',
  'AS',
  ...FUTURE_KEYWORDS.keys(),
  ...FORBIDDEN_STATEMENTS,
]);

/** Reservadas de Oracle y del subconjunto: no sirven como alias sin comillas. */
export const RESERVED_WORDS = new Set([
  ...CLAUSE_KEYWORDS,
  'ANY',
  'ASC',
  'BY',
  'CHECK',
  'COLUMN',
  'DATE',
  'DEFAULT',
  'DESC',
  'ELSE',
  'EXISTS',
  'GRANT',
  'INDEX',
  'INTO',
  'NUMBER',
  'OF',
  'OPTION',
  'PRIOR',
  'TABLE',
  'THEN',
  'TO',
  'VALUES',
  'VARCHAR2',
  'VIEW',
  'WHEN',
]);
