/** Palabras clave según su papel en el subconjunto SELECT v2 (LAB_SPEC). */

/**
 * Construcción válida en Oracle que la plataforma enseña en un nivel posterior. `topic` es
 * el identificador de su ficha en el roadmap (`/modules#tema-<topic>`), si existe.
 */
export interface FutureFeature {
  readonly label: string;
  readonly level: number | null;
  readonly topic: string | null;
}

const feature = (label: string, level: number | null, topic: string | null): FutureFeature => ({
  label,
  level,
  topic,
});

/** Palabras que abren construcciones de niveles futuros. */
export const FUTURE_KEYWORDS: ReadonlyMap<string, FutureFeature> = new Map([
  ['GROUP', feature('Agrupar filas con GROUP BY', 3, 'group-by')],
  ['HAVING', feature('Filtrar grupos con HAVING', 3, 'having')],
  ['JOIN', feature('Combinar tablas con JOIN', 4, 'inner-join')],
  ['INNER', feature('Combinar tablas con INNER JOIN', 4, 'inner-join')],
  ['LEFT', feature('Combinar tablas con LEFT OUTER JOIN', 4, 'left-join')],
  ['RIGHT', feature('Combinar tablas con RIGHT OUTER JOIN', 4, 'right-join')],
  ['FULL', feature('Combinar tablas con FULL OUTER JOIN', 4, 'full-join')],
  ['CROSS', feature('Combinar tablas con CROSS JOIN', 4, 'cross-join')],
  ['NATURAL', feature('Combinar tablas con NATURAL JOIN', 4, 'inner-join')],
  ['ON', feature('Relacionar tablas con ON', 4, 'on-using')],
  ['USING', feature('Relacionar tablas con USING', 4, 'on-using')],
  ['UNION', feature('Combinar consultas con UNION', null, null)],
  ['INTERSECT', feature('Combinar consultas con INTERSECT', null, null)],
  ['MINUS', feature('Combinar consultas con MINUS', null, null)],
  ['EXCEPT', feature('Combinar consultas con EXCEPT', null, null)],
  ['WITH', feature('Nombrar subconsultas con WITH', 5, 'subconsulta-simple')],
  ['EXISTS', feature('Comprobar subconsultas con EXISTS', 5, 'subconsulta-where')],
  ['ANY', feature('Comparar con subconsultas usando ANY', 5, 'subconsulta-where')],
  ['SOME', feature('Comparar con subconsultas usando SOME', 5, 'subconsulta-where')],
  ['CASE', feature('Expresiones condicionales con CASE', null, null)],
  ['FETCH', feature('Limitar filas con FETCH FIRST', null, null)],
  ['OFFSET', feature('Saltar filas con OFFSET', null, null)],
  ['CONNECT', feature('Consultas jerárquicas con CONNECT BY', null, null)],
  ['START', feature('Consultas jerárquicas con START WITH', null, null)],
  ['FOR', feature('Bloquear filas con FOR UPDATE', null, null)],
  ['ROWNUM', feature('La pseudocolumna ROWNUM', null, null)],
  ['ROWID', feature('La pseudocolumna ROWID', null, null)],
  ['LEVEL', feature('La pseudocolumna LEVEL', null, null)],
  ['SYSDATE', feature('La fecha del sistema con SYSDATE', 2, 'sysdate')],
  ['SYSTIMESTAMP', feature('La fecha y hora del sistema con SYSTIMESTAMP', 2, 'sysdate')],
  ['DUAL', feature('La tabla especial DUAL', 2, 'sysdate')],
  ['ESCAPE', feature('ESCAPE para buscar % o _ literales con LIKE', null, null)],
  ['PRIOR', feature('Consultas jerárquicas con PRIOR', null, null)],
]);

/** Funciones de Oracle con ficha en el roadmap: nombre → nivel y tema. */
export const FUNCTION_TOPICS: ReadonlyMap<string, FutureFeature> = new Map([
  ['UPPER', feature('La función UPPER', 2, 'upper')],
  ['LOWER', feature('La función LOWER', 2, 'lower')],
  ['INITCAP', feature('La función INITCAP', 2, 'initcap')],
  ['LENGTH', feature('La función LENGTH', 2, 'length')],
  ['SUBSTR', feature('La función SUBSTR', 2, 'substr')],
  ['CONCAT', feature('La función CONCAT', 2, null)],
  ['TRIM', feature('La función TRIM', 2, null)],
  ['REPLACE', feature('La función REPLACE', 2, null)],
  ['ROUND', feature('La función ROUND', 2, 'round')],
  ['TRUNC', feature('La función TRUNC', 2, 'trunc')],
  ['MOD', feature('La función MOD', 2, 'mod')],
  ['ABS', feature('La función ABS', 2, null)],
  ['ADD_MONTHS', feature('La función ADD_MONTHS', 2, 'add-months')],
  ['MONTHS_BETWEEN', feature('La función MONTHS_BETWEEN', 2, 'operaciones-fecha')],
  ['EXTRACT', feature('La función EXTRACT', 2, 'operaciones-fecha')],
  ['TO_CHAR', feature('La función TO_CHAR', 2, 'to-char')],
  ['TO_DATE', feature('La función TO_DATE', 2, 'to-date')],
  ['TO_NUMBER', feature('La función TO_NUMBER', 2, 'to-number')],
  ['NVL', feature('La función NVL', 2, 'nvl')],
  ['NVL2', feature('La función NVL2', 2, 'nvl')],
  ['COALESCE', feature('La función COALESCE', 2, 'coalesce')],
  ['COUNT', feature('La función de grupo COUNT', 3, 'count')],
  ['SUM', feature('La función de grupo SUM', 3, 'sum')],
  ['AVG', feature('La función de grupo AVG', 3, 'avg')],
  ['MIN', feature('La función de grupo MIN', 3, 'min-max')],
  ['MAX', feature('La función de grupo MAX', 3, 'min-max')],
]);

/** Sentencias que no son consultas: nunca llegan al motor. */
export const FORBIDDEN_STATEMENTS: ReadonlyMap<string, FutureFeature> = new Map([
  ['INSERT', feature('INSERT', 6, 'insert')],
  ['UPDATE', feature('UPDATE', 6, 'update')],
  ['DELETE', feature('DELETE', 6, 'delete')],
  ['MERGE', feature('MERGE', 6, null)],
  ['UPSERT', feature('UPSERT', null, null)],
  ['COMMIT', feature('COMMIT', 6, 'commit-rollback')],
  ['ROLLBACK', feature('ROLLBACK', 6, 'commit-rollback')],
  ['SAVEPOINT', feature('SAVEPOINT', 6, 'commit-rollback')],
  ['CREATE', feature('CREATE', 7, 'create-table')],
  ['ALTER', feature('ALTER', 7, 'alter-table')],
  ['DROP', feature('DROP', 7, 'drop-table')],
  ['TRUNCATE', feature('TRUNCATE', 7, 'drop-table')],
  ['RENAME', feature('RENAME', 7, 'alter-table')],
  ['GRANT', feature('GRANT', null, null)],
  ['REVOKE', feature('REVOKE', null, null)],
  ['BEGIN', feature('BEGIN', null, null)],
  ['DECLARE', feature('DECLARE', null, null)],
  ['EXEC', feature('EXEC', null, null)],
  ['EXECUTE', feature('EXECUTE', null, null)],
  ['CALL', feature('CALL', null, null)],
  ['LOCK', feature('LOCK', null, null)],
  ['SET', feature('SET', null, null)],
]);

/** Palabras del subconjunto con papel propio: nunca se leen como alias implícito. */
export const CLAUSE_KEYWORDS = new Set([
  'SELECT',
  'DISTINCT',
  'UNIQUE',
  'ALL',
  'FROM',
  'WHERE',
  'ORDER',
  'BY',
  'AS',
  'AND',
  'OR',
  'NOT',
  'BETWEEN',
  'IN',
  'LIKE',
  'IS',
  'NULL',
  'ASC',
  'DESC',
  ...FUTURE_KEYWORDS.keys(),
  ...FORBIDDEN_STATEMENTS.keys(),
]);

/**
 * Palabras reservadas de Oracle SQL (SQL Language Reference, apéndice «Oracle SQL Reserved
 * Words») y del subconjunto: no sirven como alias sin comillas.
 */
export const RESERVED_WORDS = new Set([
  ...CLAUSE_KEYWORDS,
  'ACCESS',
  'ADD',
  'ANY',
  'AUDIT',
  'CHAR',
  'CHECK',
  'CLUSTER',
  'COLUMN',
  'COMMENT',
  'COMPRESS',
  'CURRENT',
  'DATE',
  'DECIMAL',
  'DEFAULT',
  'ELSE',
  'EXCLUSIVE',
  'EXISTS',
  'FILE',
  'FLOAT',
  'IDENTIFIED',
  'IMMEDIATE',
  'INCREMENT',
  'INDEX',
  'INITIAL',
  'INTEGER',
  'INTO',
  'LONG',
  'MAXEXTENTS',
  'MODE',
  'MODIFY',
  'NOAUDIT',
  'NOCOMPRESS',
  'NOWAIT',
  'NUMBER',
  'OF',
  'OFFLINE',
  'ONLINE',
  'OPTION',
  'PCTFREE',
  'PUBLIC',
  'RAW',
  'RESOURCE',
  'ROW',
  'ROWS',
  'SESSION',
  'SHARE',
  'SIZE',
  'SMALLINT',
  'SUCCESSFUL',
  'SYNONYM',
  'TABLE',
  'THEN',
  'TO',
  'TRIGGER',
  'UID',
  'USER',
  'VALIDATE',
  'VALUES',
  'VARCHAR',
  'VARCHAR2',
  'VIEW',
  'WHEN',
  'WHENEVER',
]);
