-- Dataset educativo empleados-select-v1 (DATABASE_SCHEMA.md). Se ejecuta en el esquema
-- propietario (SQL_LAB_OWNER en la instalación local), nunca con la cuenta lectora.
-- Los valores coinciden con src/domain/dataset/empleados.ts; una prueba unitaria lo verifica.

CREATE TABLE EMPLEADOS (
  ID NUMBER(4, 0) CONSTRAINT EMPLEADOS_PK PRIMARY KEY CONSTRAINT EMPLEADOS_ID_POSITIVO CHECK (ID > 0),
  NOMBRE VARCHAR2(40 CHAR) NOT NULL,
  EDAD NUMBER(3, 0) NOT NULL CONSTRAINT EMPLEADOS_EDAD_RANGO CHECK (EDAD BETWEEN 0 AND 120),
  CIUDAD VARCHAR2(50 CHAR) NOT NULL,
  SALARIO NUMBER(12, 2) NOT NULL CONSTRAINT EMPLEADOS_SALARIO_NO_NEGATIVO CHECK (SALARIO >= 0),
  DEPTO VARCHAR2(40 CHAR) NOT NULL
);

INSERT INTO EMPLEADOS (ID, NOMBRE, EDAD, CIUDAD, SALARIO, DEPTO) VALUES (1, 'Ana', 25, 'Bogotá', 3000000, 'Ventas');
INSERT INTO EMPLEADOS (ID, NOMBRE, EDAD, CIUDAD, SALARIO, DEPTO) VALUES (2, 'Carlos', 35, 'Cali', 5000000, 'Sistemas');
INSERT INTO EMPLEADOS (ID, NOMBRE, EDAD, CIUDAD, SALARIO, DEPTO) VALUES (3, 'Laura', 28, 'Bogotá', 4200000, 'Sistemas');
INSERT INTO EMPLEADOS (ID, NOMBRE, EDAD, CIUDAD, SALARIO, DEPTO) VALUES (4, 'Pedro', 19, 'Medellín', 1800000, 'Ventas');
INSERT INTO EMPLEADOS (ID, NOMBRE, EDAD, CIUDAD, SALARIO, DEPTO) VALUES (5, 'María', 30, 'Cali', 3700000, 'Contabilidad');
INSERT INTO EMPLEADOS (ID, NOMBRE, EDAD, CIUDAD, SALARIO, DEPTO) VALUES (6, 'Jorge', 22, 'Bogotá', 2800000, 'Sistemas');

COMMIT;
