/**
 * Ruta académica completa (CONTENT_MAP, «Nivel actual y futuro»): el nivel 1 es la unidad
 * actual (SELECT fundamental, lecciones del Modo Estudio) y los niveles 2–7 son temas ya
 * definidos con estado «Próximamente». Es la única fuente de `/modules`, del buscador y de
 * los enlaces del laboratorio a temas futuros (`/modules#tema-<slug>`). Añadir un tema es
 * añadir una entrada: la navegación no cambia.
 *
 * Definiciones propias, verificadas con Oracle Database 19c SQL Language Reference. Los
 * ejemplos usan EMPLEADOS y, en el nivel 4, una tabla DEPARTAMENTOS que llegará con JOIN.
 */

export type LevelStage = 'AHORA' | 'SIGUIENTE NIVEL' | 'MÁS ADELANTE';
export type TopicStatus = 'current' | 'future';

export interface CurriculumLevel {
  readonly number: number;
  readonly id: string;
  readonly title: string;
  readonly stage: LevelStage;
  readonly summary: string;
  /** Progresión de ideas del nivel, por ejemplo «filas → grupos → agregación». */
  readonly progression?: string;
  readonly prerequisites: readonly number[];
}

export interface CurriculumTopic {
  readonly id: string;
  /** Ancla estable: `/modules#tema-<slug>`. */
  readonly slug: string;
  readonly title: string;
  /** Sintaxis corta para la tarjeta. */
  readonly keyword: string;
  readonly level: number;
  readonly group: string;
  readonly status: TopicStatus;
  readonly shortDefinition: string;
  readonly purpose: string;
  readonly syntax: string;
  readonly example: string;
  /** Qué hace el ejemplo sobre los datos. */
  readonly exampleNote: string;
  readonly prerequisites: readonly string[];
  readonly commonErrors: readonly string[];
  /** Estado de los datos antes y después (sentencias que modifican datos). */
  readonly before?: string;
  readonly after?: string;
  readonly warning?: string;
  readonly availableInLab: boolean;
  readonly availableInChallenge: boolean;
  /** Escena de la Exposición principal que lo presenta; solo temas actuales. */
  readonly presentationScene: string | null;
  /** Lección del Modo Estudio que lo desarrolla; solo temas actuales. */
  readonly lesson: string | null;
  /** Términos de búsqueda sin tildes. */
  readonly keywords: readonly string[];
}

export const CURRICULUM_LEVELS: readonly CurriculumLevel[] = [
  {
    number: 1,
    id: 'select',
    title: 'SELECT fundamental',
    stage: 'AHORA',
    summary:
      'Consultar una tabla: elegir columnas, calcular, poner alias, quitar repetidas, filtrar filas, tratar NULL y ordenar.',
    prerequisites: [],
  },
  {
    number: 2,
    id: 'funciones',
    title: 'Funciones SQL',
    stage: 'SIGUIENTE NIVEL',
    summary: 'Transformar valores fila por fila: textos, números, fechas, conversiones y NULL.',
    progression: 'valor de una fila → función → valor nuevo',
    prerequisites: [1],
  },
  {
    number: 3,
    id: 'agrupacion',
    title: 'Resumen y agrupación',
    stage: 'SIGUIENTE NIVEL',
    summary: 'Pasar de filas a resúmenes: contar, sumar, promediar y filtrar grupos.',
    progression: 'filas → grupos → agregación → filtro de grupos',
    prerequisites: [1, 2],
  },
  {
    number: 4,
    id: 'join',
    title: 'Relacionar tablas (JOIN)',
    stage: 'MÁS ADELANTE',
    summary: 'Combinar filas de dos tablas relacionadas por una clave.',
    progression: 'clave → pareja de filas → filas sin pareja',
    prerequisites: [1],
  },
  {
    number: 5,
    id: 'subconsultas',
    title: 'Subconsultas',
    stage: 'MÁS ADELANTE',
    summary: 'Usar el resultado de una consulta dentro de otra.',
    prerequisites: [1, 3],
  },
  {
    number: 6,
    id: 'modificar',
    title: 'Modificar datos',
    stage: 'MÁS ADELANTE',
    summary: 'Insertar, actualizar y borrar filas con control de transacciones.',
    progression: 'cambio → transacción → COMMIT o ROLLBACK',
    prerequisites: [1],
  },
  {
    number: 7,
    id: 'estructura',
    title: 'Estructura de datos (DDL)',
    stage: 'MÁS ADELANTE',
    summary: 'Crear y cambiar tablas, y proteger los datos con restricciones.',
    prerequisites: [1, 6],
  },
];

type TopicInput = Omit<
  CurriculumTopic,
  | 'status'
  | 'availableInLab'
  | 'availableInChallenge'
  | 'presentationScene'
  | 'lesson'
  | 'prerequisites'
> & { readonly prerequisites?: readonly string[] };

const future = (input: TopicInput): CurriculumTopic => ({
  ...input,
  prerequisites: input.prerequisites ?? [],
  status: 'future',
  availableInLab: false,
  availableInChallenge: false,
  presentationScene: null,
  lesson: null,
});

export const FUTURE_TOPICS: readonly CurriculumTopic[] = [
  /* ---------- Nivel 2 · Funciones ---------- */
  future({
    id: 'upper',
    slug: 'upper',
    title: 'UPPER',
    keyword: 'UPPER(texto)',
    level: 2,
    group: 'Funciones de texto',
    shortDefinition: 'Devuelve el texto en mayúsculas.',
    purpose: 'Comparar o mostrar textos sin depender de cómo se escribieron.',
    syntax: 'UPPER(texto)',
    example: 'SELECT nombre, UPPER(ciudad) AS ciudad\nFROM empleados;',
    exampleNote: "Bogotá se muestra como 'BOGOTÁ'; la tabla no cambia.",
    prerequisites: ['SELECT', 'Comparaciones'],
    commonErrors: ['Creer que UPPER cambia el dato guardado: solo cambia el valor mostrado.'],
    keywords: ['upper', 'mayusculas', 'funciones de texto'],
  }),
  future({
    id: 'lower',
    slug: 'lower',
    title: 'LOWER',
    keyword: 'LOWER(texto)',
    level: 2,
    group: 'Funciones de texto',
    shortDefinition: 'Devuelve el texto en minúsculas.',
    purpose: "Buscar sin distinguir mayúsculas: WHERE LOWER(nombre) LIKE 'a%'.",
    syntax: 'LOWER(texto)',
    example: "SELECT nombre\nFROM empleados\nWHERE LOWER(nombre) LIKE 'a%';",
    exampleNote: 'Encuentra a Ana, Andrés y Alicia aunque el patrón esté en minúscula.',
    prerequisites: ['LIKE'],
    commonErrors: ['Aplicar LOWER solo a un lado de la comparación.'],
    keywords: ['lower', 'minusculas', 'funciones de texto'],
  }),
  future({
    id: 'initcap',
    slug: 'initcap',
    title: 'INITCAP',
    keyword: 'INITCAP(texto)',
    level: 2,
    group: 'Funciones de texto',
    shortDefinition: 'Pone en mayúscula la primera letra de cada palabra y el resto en minúscula.',
    purpose: 'Presentar nombres y títulos con un formato uniforme.',
    syntax: 'INITCAP(texto)',
    example: 'SELECT nombre, INITCAP(cargo) AS cargo\nFROM empleados;',
    exampleNote: "'Líder de área' se muestra como 'Líder De Área'.",
    commonErrors: ['Esperar que respete excepciones como «de» o «del»: cambia todas las palabras.'],
    keywords: ['initcap', 'mayuscula inicial', 'funciones de texto'],
  }),
  future({
    id: 'length',
    slug: 'length',
    title: 'LENGTH',
    keyword: 'LENGTH(texto)',
    level: 2,
    group: 'Funciones de texto',
    shortDefinition: 'Devuelve cuántos caracteres tiene un texto.',
    purpose: 'Validar longitudes o buscar textos cortos y largos.',
    syntax: 'LENGTH(texto)',
    example: 'SELECT nombre, LENGTH(nombre) AS letras\nFROM empleados;',
    exampleNote: 'Ana tiene 3 letras; Valentina, 9.',
    commonErrors: ["En Oracle, LENGTH('') es NULL, no 0, porque el texto vacío es NULL."],
    keywords: ['length', 'longitud', 'caracteres', 'funciones de texto'],
  }),
  future({
    id: 'substr',
    slug: 'substr',
    title: 'SUBSTR',
    keyword: 'SUBSTR(texto, inicio, largo)',
    level: 2,
    group: 'Funciones de texto',
    shortDefinition: 'Devuelve una parte de un texto; la primera posición es 1.',
    purpose: 'Extraer iniciales, códigos o prefijos.',
    syntax: 'SUBSTR(texto, posición_inicial, cantidad)',
    example: 'SELECT nombre, SUBSTR(apellido, 1, 1) AS inicial\nFROM empleados;',
    exampleNote: "Para Ana Rojas, la inicial del apellido es 'R'.",
    commonErrors: ['Empezar a contar desde 0: en Oracle la primera posición es 1.'],
    keywords: ['substr', 'subcadena', 'parte de un texto', 'funciones de texto'],
  }),
  future({
    id: 'round',
    slug: 'round',
    title: 'ROUND',
    keyword: 'ROUND(número, decimales)',
    level: 2,
    group: 'Funciones numéricas',
    shortDefinition: 'Redondea un número a la cantidad de decimales indicada.',
    purpose: 'Presentar cálculos con decimales de forma legible.',
    syntax: 'ROUND(número [, decimales])',
    example: 'SELECT nombre, ROUND(salario / 30) AS salario_diario\nFROM empleados;',
    exampleNote:
      'Un decimal negativo redondea a decenas, centenas o miles: ROUND(1234567, -3) = 1235000.',
    commonErrors: ['Confundir ROUND (redondea) con TRUNC (corta).'],
    keywords: ['round', 'redondear', 'funciones numericas'],
  }),
  future({
    id: 'trunc',
    slug: 'trunc',
    title: 'TRUNC',
    keyword: 'TRUNC(número, decimales)',
    level: 2,
    group: 'Funciones numéricas',
    shortDefinition: 'Corta un número a los decimales indicados, sin redondear.',
    purpose: 'Quedarse con la parte entera o con cierta precisión. Con fechas, quita la hora.',
    syntax: 'TRUNC(número [, decimales])',
    example: 'SELECT nombre, TRUNC(salario / 30) AS salario_diario\nFROM empleados;',
    exampleNote: 'TRUNC(2.9) es 2; ROUND(2.9) es 3.',
    commonErrors: ['Esperar un redondeo: TRUNC siempre corta.'],
    keywords: ['trunc', 'truncar', 'funciones numericas'],
  }),
  future({
    id: 'mod',
    slug: 'mod',
    title: 'MOD',
    keyword: 'MOD(m, n)',
    level: 2,
    group: 'Funciones numéricas',
    shortDefinition: 'Devuelve el resto de dividir m entre n.',
    purpose: 'Detectar pares e impares o repartir en turnos.',
    syntax: 'MOD(dividendo, divisor)',
    example: 'SELECT nombre, id_empleado\nFROM empleados\nWHERE MOD(id_empleado, 2) = 0;',
    exampleNote: 'Devuelve los empleados con identificador par.',
    commonErrors: ['Usar % como operador de resto: en Oracle es la función MOD.'],
    keywords: ['mod', 'resto', 'modulo', 'funciones numericas'],
  }),
  future({
    id: 'sysdate',
    slug: 'sysdate',
    title: 'SYSDATE',
    keyword: 'SYSDATE',
    level: 2,
    group: 'Fechas',
    shortDefinition: 'Devuelve la fecha y la hora actuales del servidor de base de datos.',
    purpose: 'Calcular antigüedades o comparar con el día de hoy.',
    syntax: 'SYSDATE',
    example: 'SELECT nombre, TRUNC(SYSDATE - fecha_ingreso) AS dias_en_la_empresa\nFROM empleados;',
    exampleNote: 'Restar dos fechas da la cantidad de días entre ellas.',
    commonErrors: ['Olvidar que SYSDATE incluye la hora: TRUNC(SYSDATE) deja solo la fecha.'],
    keywords: ['sysdate', 'fecha actual', 'hoy', 'fechas'],
  }),
  future({
    id: 'operaciones-fecha',
    slug: 'operaciones-fecha',
    title: 'Operaciones con fechas',
    keyword: 'fecha + días',
    level: 2,
    group: 'Fechas',
    shortDefinition: 'Sumar días a una fecha o restar dos fechas.',
    purpose: 'Calcular vencimientos, periodos de prueba o antigüedades.',
    syntax: 'fecha + número_de_días\nfecha1 - fecha2',
    example: 'SELECT nombre, fecha_ingreso + 90 AS fin_periodo_prueba\nFROM empleados;',
    exampleNote: 'Suma 90 días a la fecha de ingreso de cada empleado.',
    commonErrors: [
      'Sumar meses con + 30: los meses no tienen la misma cantidad de días; se usa ADD_MONTHS.',
    ],
    keywords: ['fechas', 'sumar dias', 'restar fechas', 'date'],
  }),
  future({
    id: 'add-months',
    slug: 'add-months',
    title: 'ADD_MONTHS',
    keyword: 'ADD_MONTHS(fecha, n)',
    level: 2,
    group: 'Fechas',
    shortDefinition: 'Suma (o resta, con n negativo) una cantidad de meses a una fecha.',
    purpose: 'Programar evaluaciones o renovaciones por meses.',
    syntax: 'ADD_MONTHS(fecha, meses)',
    example: 'SELECT nombre, ADD_MONTHS(fecha_ingreso, 6) AS primera_evaluacion\nFROM empleados;',
    exampleNote: 'Seis meses después de la fecha de ingreso.',
    commonErrors: ['Pasar los meses como texto: el segundo argumento es un número.'],
    keywords: ['add_months', 'sumar meses', 'fechas'],
  }),
  future({
    id: 'to-char',
    slug: 'to-char',
    title: 'TO_CHAR',
    keyword: "TO_CHAR(valor, 'formato')",
    level: 2,
    group: 'Conversión',
    shortDefinition: 'Convierte una fecha o un número en texto con el formato indicado.',
    purpose: 'Mostrar fechas como 23/01/2017 o números con separadores.',
    syntax: "TO_CHAR(fecha, 'DD/MM/YYYY')",
    example: "SELECT nombre, TO_CHAR(fecha_ingreso, 'DD/MM/YYYY') AS ingreso\nFROM empleados;",
    exampleNote: 'La fecha se presenta con el formato elegido, sin depender de la sesión.',
    commonErrors: [
      'Comparar fechas convertidas a texto: el orden de los textos no es el de las fechas.',
    ],
    keywords: ['to_char', 'formato', 'convertir a texto', 'conversion'],
  }),
  future({
    id: 'to-date',
    slug: 'to-date',
    title: 'TO_DATE',
    keyword: "TO_DATE(texto, 'formato')",
    level: 2,
    group: 'Conversión',
    shortDefinition: 'Convierte un texto en fecha según el formato indicado.',
    purpose: 'Escribir fechas en cualquier formato de forma segura.',
    syntax: "TO_DATE('31/12/2021', 'DD/MM/YYYY')",
    example:
      "SELECT nombre\nFROM empleados\nWHERE fecha_ingreso >= TO_DATE('01/01/2020', 'DD/MM/YYYY');",
    exampleNote: "Equivale a fecha_ingreso >= DATE '2020-01-01'.",
    commonErrors: [
      'Comparar una fecha con un texto sin TO_DATE: depende del formato de la sesión.',
    ],
    keywords: ['to_date', 'convertir a fecha', 'conversion', 'fechas'],
  }),
  future({
    id: 'to-number',
    slug: 'to-number',
    title: 'TO_NUMBER',
    keyword: 'TO_NUMBER(texto)',
    level: 2,
    group: 'Conversión',
    shortDefinition: 'Convierte un texto con dígitos en número.',
    purpose: 'Calcular con valores que llegaron como texto.',
    syntax: "TO_NUMBER('3000000')",
    example: "SELECT nombre\nFROM empleados\nWHERE salario > TO_NUMBER('5000000');",
    exampleNote: 'El texto se convierte antes de comparar.',
    commonErrors: ['Convertir un texto que no es numérico: Oracle da ORA-01722.'],
    keywords: ['to_number', 'convertir a numero', 'conversion'],
  }),
  future({
    id: 'nvl',
    slug: 'nvl',
    title: 'NVL',
    keyword: 'NVL(valor, reemplazo)',
    level: 2,
    group: 'NULL',
    shortDefinition: 'Si el valor es NULL, devuelve el reemplazo; si no, el propio valor.',
    purpose: 'Calcular sin que un NULL anule el resultado.',
    syntax: 'NVL(expresión, valor_si_es_null)',
    example: 'SELECT nombre, (salario + NVL(bono, 0)) * 12 AS total_anual\nFROM empleados;',
    exampleNote: 'Los empleados sin bono cuentan con 0 y ya no tienen un total NULL.',
    prerequisites: ['NULL', 'Precedencia'],
    commonErrors: ["Usar un reemplazo de otro tipo: NVL(bono, 'sin bono') mezcla número y texto."],
    keywords: ['nvl', 'reemplazar null', 'null', 'valor por defecto'],
  }),
  future({
    id: 'coalesce',
    slug: 'coalesce',
    title: 'COALESCE',
    keyword: 'COALESCE(v1, v2, …)',
    level: 2,
    group: 'NULL',
    shortDefinition: 'Devuelve el primer valor de la lista que no es NULL.',
    purpose: 'Elegir entre varias alternativas cuando algunas faltan.',
    syntax: 'COALESCE(expresión1, expresión2, …)',
    example: 'SELECT nombre, COALESCE(bono, 0) AS bono\nFROM empleados;',
    exampleNote: 'Con dos argumentos se comporta como NVL; admite más.',
    prerequisites: ['NULL'],
    commonErrors: ['Esperar que trate el 0 como ausencia: 0 es un valor.'],
    keywords: ['coalesce', 'null', 'primer valor no nulo'],
  }),

  /* ---------- Nivel 3 · Resumen y agrupación ---------- */
  future({
    id: 'count',
    slug: 'count',
    title: 'COUNT',
    keyword: 'COUNT(*)',
    level: 3,
    group: 'Funciones de grupo',
    shortDefinition: 'Cuenta filas; COUNT(columna) cuenta solo los valores que no son NULL.',
    purpose: '¿Cuántos empleados hay? ¿Cuántos tienen bono?',
    syntax: 'COUNT(*)\nCOUNT(columna)',
    example: 'SELECT COUNT(*) AS empleados,\n       COUNT(bono) AS con_bono\nFROM empleados;',
    exampleNote: 'Devuelve una sola fila: 20 empleados y 14 con bono.',
    commonErrors: ['Esperar que COUNT(bono) cuente los NULL: los ignora.'],
    keywords: ['count', 'contar', 'cuantos', 'funciones de grupo', 'agregados'],
  }),
  future({
    id: 'sum',
    slug: 'sum',
    title: 'SUM',
    keyword: 'SUM(columna)',
    level: 3,
    group: 'Funciones de grupo',
    shortDefinition: 'Suma los valores de un grupo, ignorando los NULL.',
    purpose: 'Totales: nómina mensual, bonos pagados.',
    syntax: 'SUM(expresión)',
    example: 'SELECT SUM(salario) AS nomina_mensual\nFROM empleados;',
    exampleNote: 'Suma el salario de las 20 filas en un solo valor.',
    commonErrors: [
      'Mezclar columnas sin agrupar: SELECT ciudad, SUM(salario) exige GROUP BY ciudad.',
    ],
    keywords: ['sum', 'sumar', 'total', 'funciones de grupo', 'agregados'],
  }),
  future({
    id: 'avg',
    slug: 'avg',
    title: 'AVG',
    keyword: 'AVG(columna)',
    level: 3,
    group: 'Funciones de grupo',
    shortDefinition: 'Calcula el promedio de un grupo, ignorando los NULL.',
    purpose: 'Comparar niveles: salario promedio por departamento.',
    syntax: 'AVG(expresión)',
    example: 'SELECT AVG(salario) AS salario_promedio\nFROM empleados;',
    exampleNote: 'Un solo valor: el promedio de los 20 salarios.',
    commonErrors: ['Olvidar que AVG(bono) divide entre los 14 que tienen bono, no entre 20.'],
    keywords: ['avg', 'promedio', 'media', 'funciones de grupo', 'agregados'],
  }),
  future({
    id: 'min-max',
    slug: 'min-max',
    title: 'MIN y MAX',
    keyword: 'MIN · MAX',
    level: 3,
    group: 'Funciones de grupo',
    shortDefinition: 'Devuelven el menor y el mayor valor de un grupo.',
    purpose: 'Encontrar extremos: el salario más bajo, la fecha de ingreso más antigua.',
    syntax: 'MIN(expresión)\nMAX(expresión)',
    example: 'SELECT MIN(salario) AS minimo,\n       MAX(salario) AS maximo\nFROM empleados;',
    exampleNote: 'Funcionan con números, textos y fechas.',
    commonErrors: [
      'Esperar el nombre de quien tiene el máximo: para eso se necesita una subconsulta.',
    ],
    keywords: ['min', 'max', 'minimo', 'maximo', 'funciones de grupo', 'agregados'],
  }),
  future({
    id: 'group-by',
    slug: 'group-by',
    title: 'GROUP BY',
    keyword: 'GROUP BY',
    level: 3,
    group: 'Agrupación',
    shortDefinition: 'Forma grupos de filas con el mismo valor y resume cada grupo.',
    purpose: '¿Cuántos empleados hay por departamento? ¿Cuánto suma cada ciudad?',
    syntax: 'SELECT columna, COUNT(*)\nFROM tabla\nGROUP BY columna;',
    example: 'SELECT departamento, COUNT(*) AS empleados\nFROM empleados\nGROUP BY departamento;',
    exampleNote: 'Una fila por departamento con su cantidad de empleados.',
    prerequisites: ['COUNT'],
    commonErrors: [
      'Poner en SELECT una columna que no está en GROUP BY ni dentro de una función (ORA-00979).',
    ],
    keywords: ['group by', 'agrupar', 'grupos', 'agrupacion'],
  }),
  future({
    id: 'having',
    slug: 'having',
    title: 'HAVING',
    keyword: 'HAVING',
    level: 3,
    group: 'Agrupación',
    shortDefinition: 'Filtra grupos después de agruparlos, como WHERE filtra filas.',
    purpose: 'Quedarse con los departamentos que tienen al menos cuatro empleados.',
    syntax: 'GROUP BY columna\nHAVING condición_sobre_el_grupo',
    example:
      'SELECT departamento, COUNT(*) AS empleados\nFROM empleados\nGROUP BY departamento\nHAVING COUNT(*) >= 4;',
    exampleNote: 'WHERE descarta filas antes de agrupar; HAVING descarta grupos después.',
    prerequisites: ['GROUP BY'],
    commonErrors: ['Usar WHERE COUNT(*) >= 4: las funciones de grupo van en HAVING.'],
    keywords: ['having', 'filtrar grupos', 'agrupacion'],
  }),

  /* ---------- Nivel 4 · JOIN ---------- */
  future({
    id: 'relacionar-tablas',
    slug: 'relacionar-tablas',
    title: 'Relacionar tablas',
    keyword: 'clave → clave',
    level: 4,
    group: 'Concepto',
    shortDefinition: 'Dos tablas se relacionan cuando una guarda la clave de la otra.',
    purpose: 'No repetir datos: cada dato vive en una tabla y se une cuando se necesita.',
    syntax: 'tabla1.columna = tabla2.columna',
    example: 'SELECT e.nombre, e.id_jefe\nFROM empleados e;',
    exampleNote: 'ID_JEFE guarda el ID_EMPLEADO del jefe: EMPLEADOS se relaciona consigo misma.',
    commonErrors: ['Relacionar por columnas que no guardan la misma información.'],
    keywords: ['relaciones', 'claves', 'clave foranea', 'join', 'relacionar tablas'],
  }),
  future({
    id: 'inner-join',
    slug: 'inner-join',
    title: 'INNER JOIN',
    keyword: 'INNER JOIN … ON',
    level: 4,
    group: 'Tipos de JOIN',
    shortDefinition: 'Combina las filas que tienen pareja en las dos tablas.',
    purpose: 'Ver cada empleado junto al nombre de su jefe.',
    syntax: 'FROM tabla1 t1\nINNER JOIN tabla2 t2 ON t1.clave = t2.clave',
    example:
      'SELECT e.nombre, j.nombre AS jefe\nFROM empleados e\nINNER JOIN empleados j ON e.id_jefe = j.id_empleado;',
    exampleNote: 'Ana Rojas y Esteban Torres no aparecen: su ID_JEFE es NULL y no tienen pareja.',
    prerequisites: ['Relacionar tablas', 'Alias'],
    commonErrors: ['Olvidar la condición ON: sin ella se obtiene un producto cartesiano.'],
    keywords: ['inner join', 'join', 'combinar tablas', 'union de tablas'],
  }),
  future({
    id: 'left-join',
    slug: 'left-join',
    title: 'LEFT OUTER JOIN',
    keyword: 'LEFT JOIN',
    level: 4,
    group: 'Tipos de JOIN',
    shortDefinition: 'Todas las filas de la tabla de la izquierda, con o sin pareja.',
    purpose: 'Listar a todos los empleados, incluso a quienes no tienen jefe.',
    syntax: 'FROM tabla1\nLEFT OUTER JOIN tabla2 ON condición',
    example:
      'SELECT e.nombre, j.nombre AS jefe\nFROM empleados e\nLEFT OUTER JOIN empleados j ON e.id_jefe = j.id_empleado;',
    exampleNote: 'Las 20 filas; para Ana y Esteban, JEFE es NULL.',
    prerequisites: ['INNER JOIN', 'NULL'],
    commonErrors: ['Filtrar la tabla de la derecha en WHERE y perder las filas sin pareja.'],
    keywords: ['left join', 'left outer join', 'join externo', 'join'],
  }),
  future({
    id: 'right-join',
    slug: 'right-join',
    title: 'RIGHT OUTER JOIN',
    keyword: 'RIGHT JOIN',
    level: 4,
    group: 'Tipos de JOIN',
    shortDefinition: 'Todas las filas de la tabla de la derecha, con o sin pareja.',
    purpose: 'Ver todos los departamentos, aunque alguno no tenga empleados.',
    syntax: 'FROM tabla1\nRIGHT OUTER JOIN tabla2 ON condición',
    example:
      'SELECT e.nombre, d.departamento\nFROM empleados e\nRIGHT OUTER JOIN departamentos d ON e.departamento = d.departamento;',
    exampleNote: 'Usa la tabla DEPARTAMENTOS, que se incorporará en este nivel.',
    prerequisites: ['LEFT OUTER JOIN'],
    commonErrors: ['Confundir qué tabla es la «derecha»: la que se escribe después de JOIN.'],
    keywords: ['right join', 'right outer join', 'join'],
  }),
  future({
    id: 'full-join',
    slug: 'full-join',
    title: 'FULL OUTER JOIN',
    keyword: 'FULL JOIN',
    level: 4,
    group: 'Tipos de JOIN',
    shortDefinition: 'Todas las filas de las dos tablas, con pareja o sin ella.',
    purpose: 'Detectar datos sin relación en cualquiera de los dos lados.',
    syntax: 'FROM tabla1\nFULL OUTER JOIN tabla2 ON condición',
    example:
      'SELECT e.nombre, d.departamento\nFROM empleados e\nFULL OUTER JOIN departamentos d ON e.departamento = d.departamento;',
    exampleNote: 'Aparecen empleados sin departamento registrado y departamentos sin empleados.',
    prerequisites: ['LEFT OUTER JOIN'],
    commonErrors: ['Esperar que elimine los NULL: los produce en ambos lados.'],
    keywords: ['full join', 'full outer join', 'join'],
  }),
  future({
    id: 'cross-join',
    slug: 'cross-join',
    title: 'CROSS JOIN',
    keyword: 'CROSS JOIN',
    level: 4,
    group: 'Tipos de JOIN',
    shortDefinition:
      'Combina cada fila de una tabla con cada fila de la otra (producto cartesiano).',
    purpose: 'Generar todas las combinaciones posibles, por ejemplo empleados y turnos.',
    syntax: 'FROM tabla1\nCROSS JOIN tabla2',
    example: 'SELECT e.nombre, d.departamento\nFROM empleados e\nCROSS JOIN departamentos d;',
    exampleNote: '20 empleados × 5 departamentos = 100 filas.',
    commonErrors: ['Producirlo sin querer al olvidar la condición de un JOIN.'],
    keywords: ['cross join', 'producto cartesiano', 'combinaciones', 'join'],
  }),
  future({
    id: 'on-using',
    slug: 'on-using',
    title: 'ON y USING',
    keyword: 'ON · USING',
    level: 4,
    group: 'Condición de unión',
    shortDefinition:
      'ON escribe la condición de unión; USING la abrevia cuando la columna se llama igual en ambas tablas.',
    purpose: 'Expresar con claridad cómo se emparejan las filas.',
    syntax: 'JOIN tabla2 ON tabla1.col = tabla2.col\nJOIN tabla2 USING (col)',
    example: 'SELECT nombre, sede\nFROM empleados\nJOIN departamentos USING (departamento);',
    exampleNote: 'Con USING, la columna común se escribe sin prefijo de tabla.',
    prerequisites: ['INNER JOIN'],
    commonErrors: ['Calificar con alias una columna de USING: Oracle lo rechaza.'],
    keywords: ['on', 'using', 'condicion de union', 'join'],
  }),

  /* ---------- Nivel 5 · Subconsultas ---------- */
  future({
    id: 'subconsulta-simple',
    slug: 'subconsulta-simple',
    title: 'Subconsulta',
    keyword: '( SELECT … )',
    level: 5,
    group: 'Subconsultas',
    shortDefinition: 'Una consulta escrita entre paréntesis dentro de otra.',
    purpose: 'Responder en un paso preguntas que dependen de otro resultado.',
    syntax: 'SELECT …\nFROM tabla\nWHERE columna operador (SELECT …)',
    example:
      'SELECT nombre, salario\nFROM empleados\nWHERE salario > (SELECT AVG(salario) FROM empleados);',
    exampleNote: 'Primero se obtiene el promedio y luego se compara cada salario con él.',
    prerequisites: ['WHERE', 'AVG'],
    commonErrors: ['Olvidar los paréntesis de la subconsulta.'],
    keywords: ['subconsulta', 'subquery', 'consulta anidada'],
  }),
  future({
    id: 'subconsulta-where',
    slug: 'subconsulta-where',
    title: 'Subconsulta en WHERE',
    keyword: 'WHERE … (SELECT …)',
    level: 5,
    group: 'Subconsultas',
    shortDefinition: 'La condición de WHERE compara con el resultado de otra consulta.',
    purpose: 'Filtrar contra valores calculados en el momento.',
    syntax: 'WHERE columna > (SELECT …)',
    example:
      "SELECT nombre, salario\nFROM empleados\nWHERE salario > (SELECT salario FROM empleados WHERE nombre = 'Laura');",
    exampleNote: 'Quienes ganan más que Laura Mora.',
    prerequisites: ['Subconsulta'],
    commonErrors: ['Usar = con una subconsulta que devuelve varias filas (ORA-01427).'],
    keywords: ['subconsulta', 'where', 'subquery'],
  }),
  future({
    id: 'in-subconsulta',
    slug: 'in-subconsulta',
    title: 'IN con subconsulta',
    keyword: 'IN (SELECT …)',
    level: 5,
    group: 'Subconsultas',
    shortDefinition: 'Compara con la lista de valores que devuelve una subconsulta.',
    purpose: '¿Qué empleados son jefes de alguien?',
    syntax: 'WHERE columna IN (SELECT columna FROM …)',
    example: 'SELECT nombre\nFROM empleados\nWHERE id_empleado IN (SELECT id_jefe FROM empleados);',
    exampleNote:
      'Con NOT IN hay que cuidar los NULL: ID_JEFE tiene NULL y NOT IN no devolvería filas.',
    prerequisites: ['IN', 'Subconsulta'],
    commonErrors: ['Usar NOT IN con una subconsulta que puede devolver NULL.'],
    keywords: ['in', 'subconsulta', 'lista', 'subquery'],
  }),
  future({
    id: 'subconsulta-escalar',
    slug: 'subconsulta-escalar',
    title: 'Comparar con un valor escalar',
    keyword: '= (SELECT MAX(…))',
    level: 5,
    group: 'Subconsultas',
    shortDefinition: 'Una subconsulta que devuelve un solo valor se usa como cualquier valor.',
    purpose: 'Encontrar quién tiene el salario máximo.',
    syntax: 'WHERE columna = (SELECT MAX(columna) FROM tabla)',
    example:
      'SELECT nombre, salario\nFROM empleados\nWHERE salario = (SELECT MAX(salario) FROM empleados);',
    exampleNote: 'Devuelve a Ana Rojas, que tiene el salario más alto.',
    prerequisites: ['MIN y MAX', 'Subconsulta'],
    commonErrors: ['Esperar un valor cuando la subconsulta puede devolver varias filas.'],
    keywords: ['subconsulta escalar', 'maximo', 'subquery'],
  }),

  /* ---------- Nivel 6 · Modificar datos ---------- */
  future({
    id: 'insert',
    slug: 'insert',
    title: 'INSERT INTO',
    keyword: 'INSERT INTO … VALUES',
    level: 6,
    group: 'Modificar datos',
    shortDefinition: 'Agrega filas nuevas a una tabla.',
    purpose: 'Registrar un empleado nuevo.',
    syntax: 'INSERT INTO tabla (columna1, columna2)\nVALUES (valor1, valor2);',
    example:
      "INSERT INTO empleados (id_empleado, nombre, apellido, cargo, departamento, ciudad,\n                       salario, bono, fecha_ingreso, estado, correo, id_jefe)\nVALUES (21, 'Nora', 'Pineda', 'Analista', 'TI', 'Cali',\n        3600000, NULL, DATE '2025-06-02', 'ACTIVO', 'nora.pineda@empresa.example', 2);",
    exampleNote: 'La tabla pasa de 20 a 21 filas.',
    before: '20 filas en EMPLEADOS.',
    after: '21 filas; la nueva solo la ve tu sesión hasta hacer COMMIT.',
    warning:
      'Nombra siempre las columnas: sin la lista, el orden de los valores depende de la definición de la tabla.',
    prerequisites: ['SELECT', 'Tipos de datos'],
    commonErrors: ['Olvidar una columna NOT NULL: Oracle rechaza la fila (ORA-01400).'],
    keywords: ['insert', 'insert into', 'insertar', 'agregar filas', 'dml'],
  }),
  future({
    id: 'update',
    slug: 'update',
    title: 'UPDATE',
    keyword: 'UPDATE … SET … WHERE',
    level: 6,
    group: 'Modificar datos',
    shortDefinition: 'Cambia valores de filas existentes.',
    purpose: 'Asignar un bono a un empleado.',
    syntax: 'UPDATE tabla\nSET columna = valor\nWHERE condición;',
    example: 'UPDATE empleados\nSET bono = 100000\nWHERE id_empleado = 16;',
    exampleNote: 'Solo cambia la fila de Julián Luna.',
    before: 'BONO de Julián Luna: NULL.',
    after: 'BONO de Julián Luna: 100000. Las demás filas siguen igual.',
    warning:
      'UPDATE sin WHERE cambia todas las filas de la tabla. Revisa la condición con un SELECT antes.',
    prerequisites: ['WHERE'],
    commonErrors: ['Olvidar WHERE y actualizar la tabla completa.'],
    keywords: ['update', 'actualizar', 'modificar', 'set', 'dml'],
  }),
  future({
    id: 'delete',
    slug: 'delete',
    title: 'DELETE',
    keyword: 'DELETE FROM … WHERE',
    level: 6,
    group: 'Modificar datos',
    shortDefinition: 'Borra filas de una tabla.',
    purpose: 'Retirar registros que ya no deben estar.',
    syntax: 'DELETE FROM tabla\nWHERE condición;',
    example: "DELETE FROM empleados\nWHERE estado = 'INACTIVO';",
    exampleNote: 'Borra las 3 filas inactivas.',
    before: '20 filas.',
    after: '17 filas; con ROLLBACK, antes de COMMIT, se recuperan.',
    warning: 'DELETE sin WHERE borra todas las filas. Prueba primero la condición con SELECT.',
    prerequisites: ['WHERE'],
    commonErrors: ['Olvidar WHERE y vaciar la tabla.'],
    keywords: ['delete', 'borrar', 'eliminar filas', 'dml'],
  }),
  future({
    id: 'commit-rollback',
    slug: 'commit-rollback',
    title: 'COMMIT y ROLLBACK',
    keyword: 'COMMIT · ROLLBACK',
    level: 6,
    group: 'Transacciones',
    shortDefinition: 'COMMIT confirma los cambios de la transacción; ROLLBACK los deshace.',
    purpose: 'Controlar cuándo un cambio se vuelve definitivo y visible para los demás.',
    syntax: 'COMMIT;\nROLLBACK;',
    example: 'UPDATE empleados SET bono = 0 WHERE bono IS NULL;\nROLLBACK;',
    exampleNote: 'ROLLBACK devuelve la tabla al estado de la última confirmación.',
    before: 'Cambios pendientes, visibles solo en tu sesión.',
    after: 'Con COMMIT quedan guardados para todos; con ROLLBACK desaparecen.',
    warning:
      'En Oracle, una sentencia DDL (CREATE, ALTER, DROP) confirma la transacción en curso automáticamente.',
    prerequisites: ['INSERT INTO', 'UPDATE', 'DELETE'],
    commonErrors: ['Creer que un cambio ya es visible para otros antes del COMMIT.'],
    keywords: ['commit', 'rollback', 'transacciones', 'confirmar', 'deshacer'],
  }),

  /* ---------- Nivel 7 · Estructura de datos ---------- */
  future({
    id: 'create-table',
    slug: 'create-table',
    title: 'CREATE TABLE',
    keyword: 'CREATE TABLE',
    level: 7,
    group: 'Tablas',
    shortDefinition: 'Crea una tabla nueva con sus columnas, tipos y restricciones.',
    purpose: 'Definir dónde se guardarán los datos y qué reglas cumplen.',
    syntax: 'CREATE TABLE tabla (\n  columna TIPO restricción,\n  …\n);',
    example:
      'CREATE TABLE departamentos (\n  departamento VARCHAR2(30) PRIMARY KEY,\n  sede         VARCHAR2(30) NOT NULL,\n  presupuesto  NUMBER(12)\n);',
    exampleNote: 'Así podría crearse la tabla DEPARTAMENTOS del nivel de JOIN.',
    prerequisites: ['Tipos de datos'],
    commonErrors: ['Olvidar el tamaño de VARCHAR2: es obligatorio.'],
    keywords: ['create table', 'crear tabla', 'ddl'],
  }),
  future({
    id: 'alter-table',
    slug: 'alter-table',
    title: 'ALTER TABLE',
    keyword: 'ALTER TABLE',
    level: 7,
    group: 'Tablas',
    shortDefinition: 'Cambia la estructura de una tabla: añade, modifica o renombra columnas.',
    purpose: 'Adaptar una tabla a datos nuevos sin crearla de nuevo.',
    syntax: 'ALTER TABLE tabla ADD (columna TIPO);',
    example: 'ALTER TABLE empleados\nADD (telefono VARCHAR2(20));',
    exampleNote: 'La columna nueva aparece con NULL en todas las filas existentes.',
    prerequisites: ['CREATE TABLE'],
    commonErrors: ['Añadir una columna NOT NULL sin valor por defecto a una tabla con filas.'],
    keywords: ['alter table', 'modificar tabla', 'agregar columna', 'ddl'],
  }),
  future({
    id: 'drop-table',
    slug: 'drop-table',
    title: 'DROP TABLE',
    keyword: 'DROP TABLE',
    level: 7,
    group: 'Tablas',
    shortDefinition: 'Elimina una tabla junto con sus datos.',
    purpose: 'Retirar estructuras que ya no se usan.',
    syntax: 'DROP TABLE tabla;',
    example: 'DROP TABLE departamentos;',
    exampleNote: 'La tabla y todas sus filas dejan de existir para las consultas.',
    warning: 'Es una operación DDL: confirma la transacción y no se deshace con ROLLBACK.',
    prerequisites: ['CREATE TABLE'],
    commonErrors: ['Confundir DROP TABLE (borra la tabla) con DELETE (borra filas).'],
    keywords: ['drop table', 'eliminar tabla', 'ddl'],
  }),
  future({
    id: 'primary-key',
    slug: 'primary-key',
    title: 'PRIMARY KEY',
    keyword: 'PRIMARY KEY',
    level: 7,
    group: 'Restricciones',
    shortDefinition: 'Identifica cada fila: no admite NULL ni valores repetidos.',
    purpose: 'Distinguir cada registro sin ambigüedad.',
    syntax: 'columna TIPO PRIMARY KEY',
    example: 'id_empleado NUMBER(4) PRIMARY KEY',
    exampleNote: 'Es la clave de EMPLEADOS en el script del laboratorio.',
    commonErrors: ['Usar como clave un dato que puede cambiar o repetirse, como el nombre.'],
    keywords: ['primary key', 'clave primaria', 'pk', 'restricciones'],
  }),
  future({
    id: 'foreign-key',
    slug: 'foreign-key',
    title: 'FOREIGN KEY',
    keyword: 'REFERENCES',
    level: 7,
    group: 'Restricciones',
    shortDefinition: 'Obliga a que el valor exista en la clave de otra tabla (o de la misma).',
    purpose: 'Evitar referencias a registros que no existen.',
    syntax: 'columna TIPO REFERENCES tabla (clave)',
    example: 'id_jefe NUMBER(4) REFERENCES empleados (id_empleado)',
    exampleNote: 'Así se define ID_JEFE en EMPLEADOS: todo jefe debe ser un empleado.',
    prerequisites: ['PRIMARY KEY'],
    commonErrors: ['Borrar un registro que otros referencian: Oracle lo impide (ORA-02292).'],
    keywords: ['foreign key', 'clave foranea', 'fk', 'references', 'restricciones'],
  }),
  future({
    id: 'not-null',
    slug: 'not-null',
    title: 'NOT NULL',
    keyword: 'NOT NULL',
    level: 7,
    group: 'Restricciones',
    shortDefinition: 'Obliga a que la columna siempre tenga valor.',
    purpose: 'Garantizar los datos imprescindibles.',
    syntax: 'columna TIPO NOT NULL',
    example: 'nombre VARCHAR2(40 CHAR) NOT NULL',
    exampleNote: 'En EMPLEADOS, diez de las doce columnas son NOT NULL.',
    commonErrors: ['Confundir la restricción NOT NULL con la condición IS NOT NULL de WHERE.'],
    keywords: ['not null', 'obligatorio', 'restricciones'],
  }),
  future({
    id: 'unique',
    slug: 'unique',
    title: 'UNIQUE',
    keyword: 'UNIQUE',
    level: 7,
    group: 'Restricciones',
    shortDefinition: 'Impide valores repetidos en la columna.',
    purpose: 'Asegurar datos únicos que no son la clave, como el correo.',
    syntax: 'columna TIPO UNIQUE',
    example: 'correo VARCHAR2(60 CHAR) NOT NULL UNIQUE',
    exampleNote: 'Dos empleados no pueden tener el mismo correo.',
    commonErrors: ['Esperar que UNIQUE impida los NULL: para eso se añade NOT NULL.'],
    keywords: ['unique', 'unico', 'sin repetidos', 'restricciones'],
  }),
  future({
    id: 'check',
    slug: 'check',
    title: 'CHECK',
    keyword: 'CHECK (…)',
    level: 7,
    group: 'Restricciones',
    shortDefinition: 'Exige que cada fila cumpla una condición.',
    purpose: 'Rechazar valores imposibles, como un salario negativo.',
    syntax: 'CHECK (condición)',
    example: "CHECK (estado IN ('ACTIVO', 'INACTIVO'))",
    exampleNote: 'EMPLEADOS usa CHECK para ESTADO, SALARIO y BONO.',
    commonErrors: [
      'Escribir en CHECK una condición que dependa de otras filas: solo mira la fila.',
    ],
    keywords: ['check', 'restriccion', 'validacion', 'restricciones'],
  }),
  future({
    id: 'default',
    slug: 'default',
    title: 'DEFAULT',
    keyword: 'DEFAULT',
    level: 7,
    group: 'Restricciones',
    shortDefinition: 'Valor que se usa cuando INSERT no indica esa columna.',
    purpose: 'Completar datos habituales automáticamente.',
    syntax: 'columna TIPO DEFAULT valor',
    example: "estado VARCHAR2(8 CHAR) DEFAULT 'ACTIVO'",
    exampleNote: 'Un empleado nuevo quedaría ACTIVO si no se indica otro estado.',
    commonErrors: ['Esperar que DEFAULT reemplace un NULL escrito explícitamente en INSERT.'],
    keywords: ['default', 'valor por defecto', 'restricciones'],
  }),
];

export function levelOf(number: number): CurriculumLevel {
  const level = CURRICULUM_LEVELS.find((entry) => entry.number === number);
  if (!level) throw new Error(`Nivel desconocido: ${number}`);
  return level;
}

export function topicAnchor(topic: Pick<CurriculumTopic, 'slug'>): string {
  return `tema-${topic.slug}`;
}

export function findFutureTopic(slug: string): CurriculumTopic | undefined {
  return FUTURE_TOPICS.find((topic) => topic.slug === slug);
}

export function topicsOfLevel(number: number): readonly CurriculumTopic[] {
  return FUTURE_TOPICS.filter((topic) => topic.level === number);
}
