import type { OfficialQuestion } from '../../domain/bank/bank-builders';
import {
  afterOf,
  afterOptions,
  afterQueryOf,
  codeOf,
  errorOf,
  finalize,
  orderOptions,
  outputBody,
  outputOf,
  reviewOf,
  setupOf,
  textOptions,
  type BankQuestion,
} from './verified-bank';

/**
 * Banco oficial de la Sección 3, PL/SQL y automatización (50 preguntas): bloques 6,
 * variables 7, control 7, bucles y cursores 7, excepciones 5, subprogramas 7, paquetes 4 y
 * triggers 7. Cada salida de DBMS_OUTPUT, error o tabla que cita sale de un bloque ejecutado
 * en Oracle (lecciones S3 o bloques propios del banco S3-B-*). Distribución cognitiva:
 * 8 recordar, 20 aplicar, 22 analizar. Preguntas originales de DB LAB.
 */

const S3 = 'plsql' as const;
const review = (lesson: string) => reviewOf(S3, lesson);

const REF = {
  blocks: 'Oracle Database PL/SQL Language Reference 19c, «Overview of PL/SQL» y «Blocks».',
  declarations:
    'Oracle Database PL/SQL Language Reference 19c, «Declarations», «%TYPE Attribute» y «SELECT INTO Statement».',
  control: 'Oracle Database PL/SQL Language Reference 19c, «IF Statement» y «CASE Statement».',
  loops:
    'Oracle Database PL/SQL Language Reference 19c, «LOOP Statements» y «Explicit Cursor Declaration and Definition».',
  exceptions: 'Oracle Database PL/SQL Language Reference 19c, «PL/SQL Error Handling».',
  subprograms:
    'Oracle Database PL/SQL Language Reference 19c, «PL/SQL Subprograms», «CREATE PROCEDURE» y «CREATE FUNCTION».',
  packages: 'Oracle Database PL/SQL Language Reference 19c, «PL/SQL Packages».',
  triggers: 'Oracle Database PL/SQL Language Reference 19c, «PL/SQL Triggers» y «CREATE TRIGGER».',
} as const;

/** Código con los objetos que crea antes (procedimiento, trigger…) y el bloque. */
const withSetup = (id: string) => [...setupOf(id), codeOf(id)].join('\n\n');

const bloques: BankQuestion[] = [
  {
    key: 'S3-BLQ-01',
    level: 'recordar',
    topic: 'bloques',
    subtopic: 'Estructura mínima',
    type: 'concept',
    response: 'single',
    difficulty: 1,
    prompt: '¿Qué parte de un bloque PL/SQL es obligatoria?',
    options: textOptions([
      {
        body: 'BEGIN … END; con al menos una sentencia',
        correct: true,
        feedback: 'DECLARE y EXCEPTION son opcionales.',
      },
      {
        body: 'DECLARE, aunque no se declare nada',
        feedback: 'Solo hace falta si se declara algo.',
      },
      {
        body: 'EXCEPTION, para que el bloque no falle',
        feedback: 'Es opcional: sin ella, el error sale del bloque.',
      },
      {
        body: 'Una llamada a DBMS_OUTPUT.PUT_LINE',
        feedback: 'Sirve para ver mensajes; no es parte de la estructura.',
      },
    ]),
    explanation: 'El bloque mínimo es BEGIN, una sentencia (puede ser NULL;) y END;.',
    concept: 'Bloque PL/SQL',
    review: review('S3-L02'),
    reference: REF.blocks,
  },
  {
    key: 'S3-BLQ-02',
    level: 'aplicar',
    topic: 'bloques',
    subtopic: 'Punto y coma',
    type: 'find_error',
    response: 'single',
    difficulty: 2,
    prompt: `Oracle no compila el bloque y responde ${errorOf('S3-E-SIN-PUNTO-Y-COMA')}. ¿Qué falta?`,
    code: codeOf('S3-E-SIN-PUNTO-Y-COMA'),
    options: textOptions([
      {
        body: 'El punto y coma al final de la sentencia',
        correct: true,
        feedback: 'Oracle encuentra END donde esperaba «;».',
      },
      { body: 'La sección DECLARE antes de BEGIN', feedback: 'DECLARE es opcional.' },
      { body: 'Una sección EXCEPTION antes de END', feedback: 'EXCEPTION es opcional.' },
      {
        body: 'Un COMMIT antes de terminar el bloque',
        feedback: 'COMMIT no es parte de la sintaxis del bloque.',
      },
    ]),
    explanation:
      'Cada sentencia termina en punto y coma. PLS-00103 indica un símbolo inesperado y suele señalar la línea siguiente a la que le falta.',
    concept: 'Sintaxis del bloque',
    review: review('S3-L02'),
    reference: REF.blocks,
  },
  {
    key: 'S3-BLQ-03',
    level: 'aplicar',
    topic: 'bloques',
    subtopic: 'DBMS_OUTPUT',
    type: 'predict_result',
    response: 'single',
    difficulty: 2,
    prompt: '¿Qué escribe el bloque?',
    code: codeOf('S3-B-CONCAT-NULL'),
    options: textOptions([
      { body: 'Inicio\nANULLB', code: true, feedback: 'NULL no se escribe como la palabra NULL.' },
      {
        body: outputBody('S3-B-CONCAT-NULL'),
        code: true,
        correct: true,
        feedback: 'La concatenación trata NULL como texto vacío.',
      },
      {
        body: 'Inicio',
        code: true,
        feedback: 'La segunda línea sí se escribe: || no anula el texto.',
      },
      { body: 'Inicio\nA B', code: true, feedback: 'NULL no añade un espacio.' },
    ]),
    explanation:
      "En Oracle, 'A' || NULL || 'B' es 'AB': la concatenación ignora NULL, a diferencia de la aritmética.",
    concept: 'DBMS_OUTPUT y concatenación',
    review: review('S3-L03'),
    reference: REF.blocks,
  },
  {
    key: 'S3-BLQ-04',
    level: 'analizar',
    topic: 'bloques',
    subtopic: 'Anónimo y almacenado',
    type: 'interpret_query',
    response: 'single',
    difficulty: 3,
    prompt: 'Se ejecutan estas dos unidades. ¿Qué queda guardado en la base de datos?',
    code: withSetup('S3-E-ANONIMO-VS-ALMACENADO'),
    options: textOptions([
      {
        body: 'El procedimiento saludar; el bloque anónimo, no',
        correct: true,
        feedback: 'El anónimo se compila, se ejecuta y desaparece.',
      },
      {
        body: 'Los dos: el procedimiento y el bloque',
        feedback: 'Un bloque anónimo no queda guardado.',
      },
      { body: 'Solo el bloque anónimo, porque se ejecutó', feedback: 'Ejecutar no es guardar.' },
      {
        body: 'Nada: ninguno queda guardado sin COMMIT',
        feedback: 'CREATE PROCEDURE guarda el procedimiento al crearlo.',
      },
    ]),
    explanation:
      'CREATE PROCEDURE guarda un bloque con nombre que se puede llamar muchas veces; el bloque anónimo solo se ejecuta.',
    concept: 'Bloque anónimo',
    review: review('S3-L03'),
    reference: REF.blocks,
  },
  {
    key: 'S3-BLQ-05',
    level: 'analizar',
    topic: 'bloques',
    subtopic: 'Salto a EXCEPTION',
    type: 'interpret_query',
    response: 'single',
    difficulty: 3,
    prompt: 'No existe el empleado 99. ¿Qué escribe el bloque?',
    code: codeOf('S3-E-ESTRUCTURA'),
    options: textOptions([
      {
        body: 'Encontrado: ',
        code: true,
        feedback: 'Esa línea nunca se ejecuta: el error ocurre antes.',
      },
      {
        body: 'Encontrado: \nNo existe el empleado 99',
        code: true,
        feedback: 'Tras el error, el resto de BEGIN se salta.',
      },
      {
        body: outputBody('S3-E-ESTRUCTURA'),
        code: true,
        correct: true,
        feedback: 'El control salta al manejador NO_DATA_FOUND.',
      },
      {
        body: 'ORA-01403: no data found',
        code: true,
        feedback: 'El error se maneja: el bloque no falla.',
      },
    ]),
    explanation:
      'SELECT INTO sin filas lanza NO_DATA_FOUND; el control pasa a EXCEPTION y el manejador escribe su mensaje.',
    concept: 'Estructura del bloque',
    review: review('S3-L02'),
    reference: REF.blocks,
  },
  {
    key: 'S3-BLQ-06',
    level: 'analizar',
    topic: 'bloques',
    subtopic: 'SQL o PL/SQL',
    type: 'short_case',
    response: 'single',
    difficulty: 3,
    prompt: '¿Cuál de estas tareas se resuelve con una sola sentencia SQL, sin PL/SQL?',
    options: textOptions([
      {
        body: 'Subir 10 % el salario de todo Ventas',
        correct: true,
        feedback: 'Un UPDATE con WHERE lo hace en una sentencia.',
      },
      {
        body: 'Subir distinto según el salario y avisar si falla',
        feedback: 'Hay decisiones y manejo de errores: PL/SQL.',
      },
      {
        body: 'Recorrer a cada persona y escribir un mensaje',
        feedback: 'Recorrer y escribir paso a paso es PL/SQL.',
      },
      {
        body: 'Registrar en otra tabla cada cambio de salario',
        feedback: 'Automático ante cada cambio: un trigger.',
      },
    ]),
    explanation:
      'SQL resuelve operaciones sobre conjuntos en una sentencia; PL/SQL añade pasos, decisiones, bucles y errores.',
    concept: 'SQL y PL/SQL',
    review: review('S3-L01'),
    reference: REF.blocks,
  },
];

const variables: BankQuestion[] = [
  {
    key: 'S3-VAR-01',
    level: 'recordar',
    topic: 'variables',
    subtopic: 'Asignación',
    type: 'concept',
    response: 'single',
    difficulty: 1,
    prompt: '¿Con qué operador se asigna un valor a una variable en PL/SQL?',
    options: textOptions([
      { body: ':=', code: true, correct: true, feedback: 'v_total := 0;' },
      { body: '=', code: true, feedback: 'En PL/SQL, = compara.' },
      { body: '==', code: true, feedback: 'No existe en PL/SQL.' },
      { body: '<-', code: true, feedback: 'No existe en PL/SQL.' },
    ]),
    explanation: 'La asignación es «:=»; «=» se usa para comparar en condiciones.',
    concept: 'Variable',
    review: review('S3-L04'),
    reference: REF.declarations,
  },
  {
    key: 'S3-VAR-02',
    level: 'aplicar',
    topic: 'variables',
    subtopic: 'NULL en una variable',
    type: 'predict_result',
    response: 'single',
    difficulty: 3,
    prompt: 'Paula (ID 7) no tiene bono. ¿Qué escribe el bloque?',
    code: codeOf('S3-B-NVL-VAR'),
    options: textOptions([
      {
        body: 'Sin NVL: 4200000\nCon NVL: 4200000',
        code: true,
        feedback: '4200000 + NULL es NULL.',
      },
      {
        body: outputBody('S3-B-NVL-VAR'),
        code: true,
        correct: true,
        feedback: 'Sin NVL la suma es NULL y se concatena vacía.',
      },
      {
        body: 'Sin NVL: 0\nCon NVL: 4200000',
        code: true,
        feedback: 'NULL no se convierte en 0 sin NVL.',
      },
      {
        body: 'ORA-01403: no data found',
        code: true,
        feedback: 'La fila de Paula existe; su bono es NULL.',
      },
    ]),
    explanation:
      'Una variable puede quedar en NULL. La aritmética con NULL da NULL; NVL(v_bono, 0) lo reemplaza antes de sumar.',
    concept: 'NULL y NVL',
    review: review('S3-L04'),
    reference: REF.declarations,
  },
  {
    key: 'S3-VAR-03',
    level: 'aplicar',
    topic: 'variables',
    subtopic: 'CONSTANT',
    type: 'find_error',
    response: 'single',
    difficulty: 2,
    prompt: `Oracle no compila el bloque: ${errorOf('S3-E-CONSTANTE')}. ¿Por qué?`,
    code: codeOf('S3-E-CONSTANTE'),
    options: textOptions([
      {
        body: 'c_aumento es CONSTANT: no se puede reasignar',
        correct: true,
        feedback: 'Una constante no puede ser destino de una asignación.',
      },
      { body: 'Falta DBMS_OUTPUT para ver el valor', feedback: 'No es obligatorio escribir nada.' },
      { body: '0.20 no cabe en un NUMBER sin tamaño', feedback: 'NUMBER admite ese valor.' },
      { body: 'Las constantes deben ir en mayúsculas', feedback: 'El nombre no influye.' },
    ]),
    explanation:
      'CONSTANT fija el valor al declararlo; cualquier asignación posterior da PLS-00363.',
    concept: 'CONSTANT',
    review: review('S3-L04'),
    reference: REF.declarations,
  },
  {
    key: 'S3-VAR-04',
    level: 'aplicar',
    topic: 'variables',
    subtopic: '%TYPE',
    type: 'find_error',
    response: 'single',
    difficulty: 3,
    prompt: `El bloque falla con ${errorOf('S3-E-TYPE-TAMANO')}. ¿Qué cambio lo evita?`,
    code: codeOf('S3-E-TYPE-TAMANO'),
    options: textOptions([
      {
        body: 'Declarar v_nombre empleados.nombre%TYPE',
        code: true,
        correct: true,
        feedback: 'La variable toma el tipo y el tamaño de la columna.',
      },
      {
        body: 'Declarar v_nombre NUMBER',
        code: true,
        feedback: 'NOMBRE es texto: no cabe en un NUMBER.',
      },
      {
        body: 'Añadir EXCEPTION WHEN NO_DATA_FOUND',
        code: true,
        feedback: 'La fila existe: el problema es el tamaño.',
      },
      {
        body: 'Declarar v_nombre CONSTANT VARCHAR2(3)',
        code: true,
        feedback: 'Una constante no puede recibir el SELECT INTO.',
      },
    ]),
    explanation:
      '«Paula» no cabe en VARCHAR2(3). Anclar la variable con %TYPE evita desajustes con la columna, incluso si la tabla cambia.',
    concept: '%TYPE',
    review: review('S3-L05'),
    reference: REF.declarations,
  },
  {
    key: 'S3-VAR-05',
    level: 'analizar',
    topic: 'variables',
    subtopic: 'Alcance',
    type: 'find_error',
    response: 'single',
    difficulty: 3,
    prompt: `Oracle no compila el bloque: ${errorOf('S3-E-ALCANCE-ERROR')}. ¿Por qué?`,
    code: codeOf('S3-E-ALCANCE-ERROR'),
    options: textOptions([
      {
        body: 'v_interno solo existe dentro del bloque anidado',
        correct: true,
        feedback: 'Lo de adentro no se ve afuera.',
      },
      { body: 'Falta inicializar v_interno con :=', feedback: 'Sí se inicializa con 1.' },
      { body: 'Un bloque no puede contener otro bloque', feedback: 'Los bloques pueden anidarse.' },
      { body: 'NULL; no es una sentencia válida', feedback: 'NULL; es válida: no hace nada.' },
    ]),
    explanation:
      'Una variable existe en su bloque y en los bloques que contiene; al cerrar el bloque anidado, v_interno deja de existir.',
    concept: 'Alcance',
    review: review('S3-L06'),
    reference: REF.declarations,
  },
  {
    key: 'S3-VAR-06',
    level: 'analizar',
    topic: 'variables',
    subtopic: 'SELECT INTO',
    type: 'short_case',
    response: 'multiple',
    difficulty: 4,
    prompt:
      'Investigación (60) no tiene personas y Recursos Humanos (50) tiene tres. ¿Qué SELECT INTO terminan sin excepción?',
    options: textOptions([
      {
        body: 'SELECT nombre INTO v FROM empleados WHERE id_empleado = 6;',
        code: true,
        correct: true,
        feedback: 'Exactamente una fila.',
      },
      {
        body: 'SELECT MAX(salario) INTO v FROM empleados WHERE id_departamento = 60;',
        code: true,
        correct: true,
        feedback: `Una función de grupo siempre da una fila: ${outputOf('S3-B-MAX-VACIO')[0]}.`,
      },
      {
        body: 'SELECT nombre INTO v FROM empleados WHERE id_departamento = 50;',
        code: true,
        feedback: 'Tres filas: TOO_MANY_ROWS.',
      },
      {
        body: 'SELECT nombre INTO v FROM empleados WHERE id_departamento = 60;',
        code: true,
        feedback: 'Ninguna fila: NO_DATA_FOUND.',
      },
    ]),
    explanation:
      'SELECT INTO exige exactamente una fila. Una función de grupo sin GROUP BY devuelve una fila aunque no haya datos (con NULL).',
    concept: 'SELECT INTO',
    review: review('S3-L07'),
    reference: REF.declarations,
  },
  {
    key: 'S3-VAR-07',
    level: 'aplicar',
    topic: 'variables',
    subtopic: 'SQL%ROWCOUNT',
    type: 'predict_result',
    response: 'single',
    difficulty: 2,
    prompt: 'Recursos Humanos (50) tiene tres personas. ¿Qué escribe el bloque?',
    code: codeOf('S3-E-UPDATE-ROWCOUNT'),
    options: textOptions([
      {
        body: 'Filas actualizadas: 1',
        code: true,
        feedback: 'SQL%ROWCOUNT cuenta todas las filas del UPDATE.',
      },
      {
        body: 'Filas actualizadas: 2',
        code: true,
        feedback: 'NVL incluye también a Julián, que no tenía bono.',
      },
      {
        body: outputBody('S3-E-UPDATE-ROWCOUNT'),
        code: true,
        correct: true,
        feedback: 'Las tres personas del departamento 50.',
      },
      { body: 'Filas actualizadas: 0', code: true, feedback: 'El WHERE sí encuentra filas.' },
    ]),
    explanation:
      'SQL%ROWCOUNT, justo después de un DML, dice cuántas filas afectó. El cambio queda pendiente hasta COMMIT o ROLLBACK.',
    concept: 'Cursor implícito',
    review: review('S3-L08'),
    reference: REF.declarations,
  },
];

const control: BankQuestion[] = [
  {
    key: 'S3-CTL-01',
    level: 'recordar',
    topic: 'control',
    subtopic: 'ELSIF',
    type: 'concept',
    response: 'single',
    difficulty: 1,
    prompt: '¿Cómo se escribe la rama intermedia de un IF en PL/SQL?',
    options: textOptions([
      { body: 'ELSIF', code: true, correct: true, feedback: 'IF … ELSIF … ELSE … END IF;' },
      { body: 'ELSEIF', code: true, feedback: 'No existe: es ELSIF.' },
      { body: 'ELSE IF', code: true, feedback: 'Abre un IF nuevo que necesita su propio END IF.' },
      { body: 'ELIF', code: true, feedback: 'Eso es de otros lenguajes.' },
    ]),
    explanation: 'La palabra es ELSIF (sin la segunda E).',
    concept: 'IF',
    review: review('S3-L09'),
    reference: REF.control,
  },
  {
    key: 'S3-CTL-02',
    level: 'aplicar',
    topic: 'control',
    subtopic: 'IF con cero',
    type: 'predict_result',
    response: 'single',
    difficulty: 2,
    prompt: 'Mario (ID 10) tiene bono 0. ¿Qué escribe el bloque?',
    code: codeOf('S3-B-IF-BONO-CERO'),
    options: textOptions([
      { body: 'Con bono', code: true, feedback: '0 > 0 es falso.' },
      {
        body: outputBody('S3-B-IF-BONO-CERO'),
        code: true,
        correct: true,
        feedback: 'La segunda condición es la primera verdadera.',
      },
      { body: 'Sin bono registrado', code: true, feedback: '0 es un valor, no NULL.' },
      { body: 'Con bono\nBono en cero', code: true, feedback: 'IF ejecuta una sola rama.' },
    ]),
    explanation:
      'El IF evalúa las condiciones en orden y ejecuta la primera verdadera; 0 = 0 es verdadera.',
    concept: 'IF … ELSIF',
    review: review('S3-L09'),
    reference: REF.control,
  },
  {
    key: 'S3-CTL-03',
    level: 'analizar',
    topic: 'control',
    subtopic: 'IF con NULL',
    type: 'predict_result',
    response: 'single',
    difficulty: 3,
    prompt: 'El mismo bloque con Paula (ID 7), que no tiene bono. ¿Qué escribe?',
    code: codeOf('S3-B-IF-BONO-NULL'),
    options: textOptions([
      { body: 'Bono en cero', code: true, feedback: 'NULL = 0 no es verdadero.' },
      { body: 'Con bono', code: true, feedback: 'NULL > 0 no es verdadero.' },
      {
        body: outputBody('S3-B-IF-BONO-NULL'),
        code: true,
        correct: true,
        feedback: 'Ninguna condición es TRUE: se ejecuta ELSE.',
      },
      { body: '(nada)', feedback: 'El ELSE sí escribe una línea.' },
    ]),
    explanation:
      'Toda comparación con NULL es desconocida; ninguna rama se cumple y el control llega a ELSE.',
    concept: 'IF y NULL',
    review: review('S3-L09'),
    reference: REF.control,
  },
  {
    key: 'S3-CTL-04',
    level: 'aplicar',
    topic: 'control',
    subtopic: 'END IF',
    type: 'find_error',
    response: 'single',
    difficulty: 2,
    prompt: `Oracle no compila el bloque: ${errorOf('S3-E-SIN-END-IF')}. ¿Qué falta?`,
    code: codeOf('S3-E-SIN-END-IF'),
    options: textOptions([
      {
        body: 'END IF; para cerrar el IF',
        correct: true,
        feedback: 'Cada IF termina con END IF;.',
      },
      { body: 'Un ELSE obligatorio', feedback: 'ELSE es opcional en un IF.' },
      { body: 'THEN después de la condición', feedback: 'THEN ya está escrito.' },
      { body: 'Paréntesis en la condición', feedback: 'Son opcionales.' },
    ]),
    explanation: 'Oracle llega a END; esperando END IF;: el IF quedó abierto.',
    concept: 'IF',
    review: review('S3-L09'),
    reference: REF.control,
  },
  {
    key: 'S3-CTL-05',
    level: 'analizar',
    topic: 'control',
    subtopic: 'CASE sin ELSE',
    type: 'interpret_query',
    response: 'single',
    difficulty: 4,
    prompt: `Ricardo no tiene asignaciones y el bloque termina con ${errorOf('S3-E-CASE-NOT-FOUND')}. ¿Por qué?`,
    code: codeOf('S3-E-CASE-NOT-FOUND'),
    options: textOptions([
      {
        body: 'v_horas es NULL y la sentencia no tiene ELSE',
        correct: true,
        feedback: 'Ninguna rama se ejecuta: CASE_NOT_FOUND.',
      },
      {
        body: 'SELECT INTO no encontró ninguna fila de Ricardo',
        feedback: 'SUM siempre devuelve una fila (aquí con NULL).',
      },
      {
        body: 'Un CASE no admite condiciones con >= ni >',
        feedback: 'El CASE de búsqueda admite cualquier condición.',
      },
      {
        body: 'Falta un END IF dentro de cada rama WHEN',
        feedback: 'La sentencia CASE termina con END CASE.',
      },
    ]),
    explanation:
      'Una sentencia CASE debe ejecutar alguna rama. Sin coincidencias y sin ELSE, Oracle lanza ORA-06592.',
    concept: 'CASE',
    review: review('S3-L10'),
    reference: REF.control,
  },
  {
    key: 'S3-CTL-06',
    level: 'aplicar',
    topic: 'control',
    subtopic: 'CASE simple',
    type: 'predict_result',
    response: 'single',
    difficulty: 2,
    prompt:
      'Camila (ID 13) es de Finanzas (40) y trabaja en un proyecto de TI. ¿Qué escribe el bloque?',
    code: codeOf('S3-B-CASE-SIMPLE'),
    options: textOptions([
      {
        body: 'Camila: Tecnología',
        code: true,
        feedback: 'El CASE mira su departamento, no sus proyectos.',
      },
      { body: 'Camila: Otra área', code: true, feedback: 'El 40 sí tiene su WHEN.' },
      {
        body: outputBody('S3-B-CASE-SIMPLE'),
        code: true,
        correct: true,
        feedback: 'v_depto vale 40.',
      },
      {
        body: 'ORA-06592: CASE not found',
        code: true,
        feedback: 'Hay coincidencia, y además hay ELSE.',
      },
    ]),
    explanation:
      'El CASE simple compara un valor con cada WHEN y devuelve el de la primera coincidencia.',
    concept: 'CASE simple',
    review: review('S3-L10'),
    reference: REF.control,
  },
  {
    key: 'S3-CTL-07',
    level: 'analizar',
    topic: 'control',
    subtopic: 'Expresión CASE sin ELSE',
    type: 'interpret_query',
    response: 'single',
    difficulty: 4,
    prompt:
      'A diferencia de la sentencia CASE, ¿qué hace esta expresión CASE cuando ningún WHEN coincide?',
    code: codeOf('S3-B-CASE-EXPR'),
    options: textOptions([
      {
        body: 'Devuelve NULL y el bloque sigue',
        correct: true,
        feedback: `Escribe «${outputOf('S3-B-CASE-EXPR')[0]}».`,
      },
      {
        body: 'Lanza ORA-06592 como la sentencia',
        feedback: 'Eso solo ocurre con la sentencia CASE.',
      },
      {
        body: 'Devuelve el valor del primer WHEN',
        feedback: 'Solo devuelve un WHEN que coincide.',
      },
      {
        body: 'Devuelve el número 60 como texto',
        feedback: 'Devuelve NULL, no el valor comparado.',
      },
    ]),
    explanation:
      'La expresión CASE sin ELSE devuelve NULL si nada coincide; la sentencia CASE sin ELSE lanza CASE_NOT_FOUND.',
    concept: 'Expresión CASE',
    review: review('S3-L10'),
    reference: REF.control,
  },
];

const cursores: BankQuestion[] = [
  {
    key: 'S3-CUR-01',
    level: 'recordar',
    topic: 'cursores',
    subtopic: 'Cursor FOR',
    type: 'concept',
    response: 'single',
    difficulty: 1,
    prompt: '¿Qué hace un cursor FOR LOOP por ti?',
    options: textOptions([
      {
        body: 'Abre, lee cada fila y cierra el cursor',
        correct: true,
        feedback: 'Y declara el registro de la fila.',
      },
      {
        body: 'Solo abre el cursor; el FETCH es manual',
        feedback: 'También hace el FETCH en cada vuelta.',
      },
      { body: 'Lee una fila y termina', feedback: 'Recorre todas las filas.' },
      {
        body: 'Ordena las filas por la clave',
        feedback: 'El orden lo da el ORDER BY de la consulta.',
      },
    ]),
    explanation: 'El cursor FOR abre, recorre con FETCH y cierra automáticamente.',
    concept: 'Cursor FOR LOOP',
    review: review('S3-L15'),
    reference: REF.loops,
  },
  {
    key: 'S3-CUR-02',
    level: 'analizar',
    topic: 'cursores',
    subtopic: 'LOOP con EXIT WHEN',
    type: 'predict_result',
    response: 'single',
    difficulty: 4,
    prompt: '¿Qué escribe la última línea del bloque?',
    code: codeOf('S3-B-LOOP-EXIT'),
    options: textOptions([
      { body: 'Fin con 6', code: true, feedback: 'El valor sigue creciendo antes del EXIT.' },
      {
        body: outputOf('S3-B-LOOP-EXIT').at(-1)!,
        code: true,
        correct: true,
        feedback: 'v_i llega a 8, EXIT sale y se escribe 8.',
      },
      { body: 'Fin con 7', code: true, feedback: 'v_i avanza de 2 en 2.' },
      { body: 'Fin con 10', code: true, feedback: 'El bucle sale en cuanto v_i supera 6.' },
    ]),
    explanation:
      'v_i toma 2, 4 y 6 (se escriben); en la cuarta vuelta vale 8, EXIT WHEN v_i > 6 sale antes de escribir y la línea final muestra 8.',
    concept: 'LOOP y EXIT WHEN',
    review: review('S3-L11'),
    reference: REF.loops,
  },
  {
    key: 'S3-CUR-03',
    level: 'aplicar',
    topic: 'cursores',
    subtopic: 'FOR REVERSE',
    type: 'predict_result',
    response: 'single',
    difficulty: 2,
    prompt: '¿Qué escribe el bloque?',
    code: codeOf('S3-B-FOR-REVERSE'),
    options: textOptions([
      { body: '1\n2\n3', code: true, feedback: 'REVERSE recorre el rango al revés.' },
      { body: outputBody('S3-B-FOR-REVERSE'), code: true, correct: true, feedback: 'De 3 a 1.' },
      { body: '3\n2\n1\n0', code: true, feedback: 'El rango es 1..3: no incluye el 0.' },
      { body: '(nada)', feedback: 'Con REVERSE, 1..3 sí tiene valores.' },
    ]),
    explanation: 'FOR i IN REVERSE 1..3 recorre 3, 2 y 1: el rango se escribe de menor a mayor.',
    concept: 'FOR LOOP',
    review: review('S3-L12'),
    reference: REF.loops,
  },
  {
    key: 'S3-CUR-04',
    level: 'aplicar',
    topic: 'cursores',
    subtopic: 'Cursor explícito',
    type: 'order_fragments',
    response: 'order',
    difficulty: 3,
    prompt: 'Ordena el recorrido de un cursor explícito.',
    options: orderOptions([
      'OPEN c_personas;',
      'LOOP',
      'FETCH c_personas INTO v_nombre;',
      'EXIT WHEN c_personas%NOTFOUND;',
      'DBMS_OUTPUT.PUT_LINE(v_nombre);',
      'END LOOP;',
      'CLOSE c_personas;',
    ]),
    explanation: 'Abrir, leer una fila, salir si no hay más, procesar, repetir y cerrar.',
    concept: 'Cursor explícito',
    review: review('S3-L14'),
    reference: REF.loops,
  },
  {
    key: 'S3-CUR-05',
    level: 'analizar',
    topic: 'cursores',
    subtopic: 'Cursor sin abrir',
    type: 'find_error',
    response: 'single',
    difficulty: 3,
    prompt: `El bloque falla con ${errorOf('S3-E-CURSOR-CERRADO')}. ¿Por qué?`,
    code: codeOf('S3-E-CURSOR-CERRADO'),
    options: textOptions([
      {
        body: 'Se hace FETCH sin haber hecho OPEN',
        correct: true,
        feedback: 'Un cursor debe abrirse antes de leer.',
      },
      { body: 'Falta el CLOSE al final', feedback: 'El error ocurre antes, en el FETCH.' },
      { body: 'La consulta no tiene WHERE', feedback: 'Un cursor puede recorrer toda la tabla.' },
      { body: 'v_nombre debe ser VARCHAR2(30)', feedback: '%TYPE ya ajusta el tipo.' },
    ]),
    explanation:
      'OPEN ejecuta la consulta del cursor; sin él, FETCH no tiene filas que leer (ORA-01001).',
    concept: 'Cursor explícito',
    review: review('S3-L14'),
    reference: REF.loops,
  },
  {
    key: 'S3-CUR-06',
    level: 'analizar',
    topic: 'cursores',
    subtopic: '%ROWCOUNT',
    type: 'predict_result',
    response: 'single',
    difficulty: 4,
    prompt:
      'Hay seis analistas; dos de ellos (Oscar y Diego) están inactivos. ¿Qué escribe el bloque?',
    code: codeOf('S3-B-CURSOR-ROWCOUNT'),
    options: textOptions([
      { body: 'Leídas: 5', code: true, feedback: 'El FETCH fallido no cuenta como fila leída.' },
      { body: 'Leídas: 6', code: true, feedback: 'La consulta filtra a los activos.' },
      {
        body: outputBody('S3-B-CURSOR-ROWCOUNT'),
        code: true,
        correct: true,
        feedback: 'Cuatro analistas activos leídos.',
      },
      {
        body: 'Leídas: 0',
        code: true,
        feedback: '%ROWCOUNT acumula las filas leídas hasta ahora.',
      },
    ]),
    explanation:
      '%ROWCOUNT cuenta las filas obtenidas con éxito; el último FETCH, que no trae fila, no suma.',
    concept: 'Atributos de cursor',
    review: review('S3-L14'),
    reference: REF.loops,
  },
  {
    key: 'S3-CUR-07',
    level: 'aplicar',
    topic: 'cursores',
    subtopic: 'Cursor implícito',
    type: 'predict_result',
    response: 'single',
    difficulty: 3,
    prompt:
      'Ventas tiene cuatro representantes comerciales y no existe el ID 99. ¿Qué escribe el bloque?',
    code: codeOf('S3-E-IMPLICITO'),
    options: textOptions([
      {
        body: outputBody('S3-E-IMPLICITO'),
        code: true,
        correct: true,
        feedback: 'SQL% describe cada vez la última sentencia.',
      },
      {
        body: 'Aumento aplicado a 4 personas',
        code: true,
        feedback: 'La segunda parte también escribe: SQL%NOTFOUND es TRUE.',
      },
      {
        body: 'Aumento aplicado a 5 personas\nNinguna fila con ID 99',
        code: true,
        feedback: 'María es líder, no representante comercial.',
      },
      {
        body: 'Aumento aplicado a 4 personas\nORA-01403: no data found',
        code: true,
        feedback: 'Un UPDATE sin filas no lanza NO_DATA_FOUND.',
      },
    ]),
    explanation:
      'Tras el primer UPDATE, SQL%ROWCOUNT vale 4. Tras el segundo, SQL%NOTFOUND es TRUE: no hay error, solo cero filas.',
    concept: 'Cursor implícito',
    review: review('S3-L13'),
    reference: REF.loops,
  },
];

const excepciones: BankQuestion[] = [
  {
    key: 'S3-EXC-01',
    level: 'recordar',
    topic: 'excepciones',
    subtopic: 'Excepciones predefinidas',
    type: 'concept',
    response: 'single',
    difficulty: 1,
    prompt: '¿Qué excepción lanza un SELECT INTO que no encuentra ninguna fila?',
    options: textOptions([
      { body: 'NO_DATA_FOUND', code: true, correct: true, feedback: 'ORA-01403.' },
      { body: 'TOO_MANY_ROWS', code: true, feedback: 'Esa es para más de una fila.' },
      { body: 'ZERO_DIVIDE', code: true, feedback: 'Esa es para dividir entre cero.' },
      { body: 'CASE_NOT_FOUND', code: true, feedback: 'Esa es de la sentencia CASE.' },
    ]),
    explanation: 'Sin filas: NO_DATA_FOUND (ORA-01403); con varias: TOO_MANY_ROWS (ORA-01422).',
    concept: 'Excepciones predefinidas',
    review: review('S3-L16'),
    reference: REF.exceptions,
  },
  {
    key: 'S3-EXC-02',
    level: 'aplicar',
    topic: 'excepciones',
    subtopic: 'Manejador que coincide',
    type: 'predict_result',
    response: 'single',
    difficulty: 3,
    prompt: 'Cinco personas trabajan en Medellín. ¿Qué escribe el bloque?',
    code: codeOf('S3-B-EXC-VARIAS'),
    options: textOptions([
      {
        body: 'Una persona: María',
        code: true,
        feedback: 'SELECT INTO no elige una fila: falla con varias.',
      },
      {
        body: 'Nadie en Medellín',
        code: true,
        feedback: 'Hay personas: el problema es que son varias.',
      },
      {
        body: outputBody('S3-B-EXC-VARIAS'),
        code: true,
        correct: true,
        feedback: 'TOO_MANY_ROWS tiene su propio manejador.',
      },
      {
        body: 'Otro error',
        code: true,
        feedback: 'OTHERS solo atrapa lo que no atrapan los anteriores.',
      },
    ]),
    explanation:
      'Oracle busca el primer manejador que coincide con la excepción; OTHERS es el último recurso.',
    concept: 'EXCEPTION',
    review: review('S3-L16'),
    reference: REF.exceptions,
  },
  {
    key: 'S3-EXC-03',
    level: 'aplicar',
    topic: 'excepciones',
    subtopic: 'RAISE_APPLICATION_ERROR',
    type: 'interpret_query',
    response: 'single',
    difficulty: 3,
    prompt: 'Andrés ya tiene 30 horas asignadas. ¿Cómo termina el bloque?',
    code: codeOf('S3-E-RAISE-APP'),
    options: textOptions([
      {
        body: `Con ${errorOf('S3-E-RAISE-APP')} y el mensaje de la regla`,
        correct: true,
        feedback: 'El error propio llega a quien ejecuta el bloque.',
      },
      {
        body: 'Escribe el mensaje y termina sin error',
        feedback: 'RAISE_APPLICATION_ERROR termina con un error.',
      },
      {
        body: 'Con ORA-01422, porque hay varias horas',
        feedback: 'La suma devuelve una sola fila.',
      },
      {
        body: 'No hace nada: 30 no supera el límite',
        feedback: 'La regla rechaza llegar a 30 o más.',
      },
    ]),
    explanation:
      'RAISE_APPLICATION_ERROR(-20001, …) detiene el bloque con un código propio (entre -20000 y -20999) y un mensaje claro.',
    concept: 'RAISE_APPLICATION_ERROR',
    review: review('S3-L17'),
    reference: REF.exceptions,
  },
  {
    key: 'S3-EXC-04',
    level: 'analizar',
    topic: 'excepciones',
    subtopic: 'WHEN OTHERS',
    type: 'interpret_query',
    response: 'single',
    difficulty: 3,
    prompt: '¿Qué buena práctica muestra el manejador de este bloque?',
    code: codeOf('S3-E-OTHERS'),
    options: textOptions([
      {
        body: 'Muestra SQLCODE y SQLERRM: no oculta la causa',
        correct: true,
        feedback: `Escribe «${outputOf('S3-E-OTHERS')[0]}».`,
      },
      {
        body: 'Evita la división por cero antes de calcular',
        feedback: 'La división ocurre; el manejador reacciona después.',
      },
      { body: 'Atrapa solo la división por cero', feedback: 'OTHERS atrapa cualquier error.' },
      {
        body: 'Deshace la transacción automáticamente',
        feedback: 'No hay ROLLBACK en el manejador.',
      },
    ]),
    explanation:
      'Un WHEN OTHERS que solo escribe «error» esconde el problema. Mostrar SQLCODE y SQLERRM (o volver a lanzar) conserva la causa real.',
    concept: 'WHEN OTHERS',
    review: review('S3-L16'),
    reference: REF.exceptions,
  },
  {
    key: 'S3-EXC-05',
    level: 'analizar',
    topic: 'excepciones',
    subtopic: 'Excepción propia sin manejar',
    type: 'interpret_query',
    response: 'single',
    difficulty: 4,
    prompt: '¿Qué responde Oracle al ejecutar este bloque?',
    code: codeOf('S3-B-EXC-NO-MANEJADA'),
    options: textOptions([
      {
        body: `${errorOf('S3-B-EXC-NO-MANEJADA')}: excepción del usuario sin manejar`,
        correct: true,
        feedback: 'Nadie atrapa e_sin_horas.',
      },
      {
        body: 'Nada: una excepción propia no es un error',
        feedback: 'Si se lanza y no se maneja, el bloque falla.',
      },
      { body: 'ORA-20000: mensaje vacío', feedback: 'Eso sería RAISE_APPLICATION_ERROR.' },
      {
        body: 'PLS-00201: e_sin_horas no está declarada',
        feedback: 'Sí está declarada en DECLARE.',
      },
    ]),
    explanation:
      'Una excepción declarada y lanzada con RAISE debe tener un manejador WHEN e_sin_horas; si no, el bloque termina con ORA-06510.',
    concept: 'Excepción definida por el usuario',
    review: review('S3-L17'),
    reference: REF.exceptions,
  },
];

const subprogramas: BankQuestion[] = [
  {
    key: 'S3-SUB-01',
    level: 'recordar',
    topic: 'subprogramas',
    subtopic: 'Procedimiento y función',
    type: 'concept',
    response: 'single',
    difficulty: 1,
    prompt: '¿Qué distingue a una función de un procedimiento?',
    options: textOptions([
      {
        body: 'Devuelve un valor con RETURN',
        correct: true,
        feedback: 'Por eso puede usarse en expresiones y en SQL.',
      },
      { body: 'No puede recibir parámetros', feedback: 'Las funciones reciben parámetros.' },
      { body: 'No queda guardada en la base', feedback: 'CREATE FUNCTION la guarda.' },
      { body: 'Solo puede llamarse desde un trigger', feedback: 'Se llama desde PL/SQL o SQL.' },
    ]),
    explanation: 'Una función calcula y devuelve un valor; un procedimiento realiza una acción.',
    concept: 'Función',
    review: review('S3-L21'),
    reference: REF.subprograms,
  },
  {
    key: 'S3-SUB-02',
    level: 'aplicar',
    topic: 'subprogramas',
    subtopic: 'Parámetros OUT',
    type: 'predict_result',
    response: 'single',
    difficulty: 3,
    prompt:
      'Finanzas (40) tiene cuatro personas con salario promedio de 5.650.000. ¿Qué escribe el bloque?',
    code: withSetup('S3-E-PARAMETROS'),
    options: textOptions([
      {
        body: 'Finanzas:  personas, promedio ',
        code: true,
        feedback: 'Los OUT sí reciben valores al terminar.',
      },
      {
        body: outputBody('S3-E-PARAMETROS'),
        code: true,
        correct: true,
        feedback: 'El procedimiento escribe en v_total y v_promedio.',
      },
      {
        body: 'Finanzas: 40 personas, promedio 5650000',
        code: true,
        feedback: '40 es el ID que entra por el parámetro IN.',
      },
      {
        body: 'Finanzas: 3 personas, promedio 5800000',
        code: true,
        feedback: 'El procedimiento no filtra por estado.',
      },
    ]),
    explanation: 'Los parámetros OUT devuelven valores a las variables de quien llama.',
    concept: 'IN, OUT e IN OUT',
    review: review('S3-L19'),
    reference: REF.subprograms,
  },
  {
    key: 'S3-SUB-03',
    level: 'aplicar',
    topic: 'subprogramas',
    subtopic: 'Literal en un OUT',
    type: 'find_error',
    response: 'single',
    difficulty: 3,
    prompt: `Oracle no compila la llamada: ${errorOf('S3-E-OUT-LITERAL')}. ¿Por qué?`,
    code: codeOf('S3-E-OUT-LITERAL'),
    options: textOptions([
      {
        body: 'Un parámetro OUT necesita una variable',
        correct: true,
        feedback: 'El 5 no puede recibir un resultado.',
      },
      { body: 'El procedimiento no existe', feedback: 'Existe: el error es de asignación.' },
      { body: 'Los parámetros van en otro orden', feedback: 'El problema es el modo OUT.' },
      { body: 'Falta escribir EXEC antes', feedback: 'Dentro de un bloque se llama sin EXEC.' },
    ]),
    explanation: 'Un OUT o IN OUT escribe en el argumento: debe ser una variable, no un literal.',
    concept: 'Modos de parámetro',
    review: review('S3-L19'),
    reference: REF.subprograms,
  },
  {
    key: 'S3-SUB-04',
    level: 'analizar',
    topic: 'subprogramas',
    subtopic: 'Procedimiento en SQL',
    type: 'find_error',
    response: 'single',
    difficulty: 3,
    prompt: `La consulta falla con ${errorOf('S3-E-PROC-EN-SQL')}. ¿Por qué?`,
    code: codeOf('S3-E-PROC-EN-SQL'),
    options: textOptions([
      {
        body: 'Es un procedimiento: no devuelve valor',
        correct: true,
        feedback: 'SQL solo puede llamar funciones.',
      },
      { body: 'Falta el FROM completo de la consulta', feedback: 'Sí tiene FROM dual.' },
      {
        body: 'El porcentaje 5 debe escribirse 0.05',
        feedback: 'El porcentaje no causa el error.',
      },
      { body: 'DUAL no admite llamadas a programas', feedback: 'Admite funciones.' },
    ]),
    explanation:
      'Un procedimiento se ejecuta como sentencia (BEGIN aumentar_salario(6, 5); END;). En un SELECT, Oracle lo trata como identificador no válido.',
    concept: 'Procedimiento',
    review: review('S3-L21'),
    reference: REF.subprograms,
  },
  {
    key: 'S3-SUB-05',
    level: 'analizar',
    topic: 'subprogramas',
    subtopic: 'RETURN en todas las ramas',
    type: 'interpret_query',
    response: 'single',
    difficulty: 4,
    prompt: `Llamada con 2.100.000, la función falla con ${errorOf('S3-E-FUNCION-SIN-RETURN')}. ¿Por qué?`,
    code: withSetup('S3-E-FUNCION-SIN-RETURN'),
    options: textOptions([
      {
        body: 'Ninguna rama ejecuta RETURN para ese valor',
        correct: true,
        feedback: 'Falta un ELSE con RETURN.',
      },
      { body: 'Una función no admite sentencias IF', feedback: 'Admite cualquier lógica.' },
      {
        body: 'El RETURN VARCHAR2 debe llevar tamaño',
        feedback: 'En RETURN se escribe sin tamaño.',
      },
      {
        body: 'DBMS_OUTPUT no acepta llamadas a funciones',
        feedback: 'Acepta cualquier expresión de texto.',
      },
    ]),
    explanation:
      'Toda ruta de una función debe terminar en RETURN; si llega al END sin devolver nada, Oracle responde ORA-06503.',
    concept: 'Función',
    review: review('S3-L20'),
    reference: REF.subprograms,
  },
  {
    key: 'S3-SUB-06',
    level: 'aplicar',
    topic: 'subprogramas',
    subtopic: 'Función en SQL',
    type: 'single_choice',
    response: 'single',
    difficulty: 3,
    prompt: `Julián gana 2.300.000 y no tiene bono. Con esta función creada, ¿qué valor da para él la consulta «${afterQueryOf('S3-E-FUNCION-EN-SQL')}»?`,
    code: codeOf('S3-E-FUNCION-EN-SQL'),
    options: textOptions([
      {
        body: String(afterOf('S3-E-FUNCION-EN-SQL').rows.find((row) => row[0] === 'Julián')?.[1]),
        correct: true,
        feedback: '(2.300.000 + 0) × 12.',
      },
      { body: 'NULL', feedback: 'La función usa NVL(v_bono, 0).' },
      { body: '2300000', feedback: 'La función multiplica por 12.' },
      { body: '28800000', feedback: 'Julián no tiene bono que sumar.' },
    ]),
    explanation: 'La función se ejecuta para cada fila de la consulta, como una columna calculada.',
    concept: 'Función en SQL',
    review: review('S3-L20'),
    reference: REF.subprograms,
  },
  {
    key: 'S3-SUB-07',
    level: 'analizar',
    topic: 'subprogramas',
    subtopic: 'IN OUT',
    type: 'predict_result',
    response: 'single',
    difficulty: 4,
    prompt: '¿Qué escribe el bloque?',
    code: withSetup('S3-E-IN-OUT'),
    options: textOptions([
      { body: 'Bono con tope: 900000', code: true, feedback: 'IN OUT devuelve el valor cambiado.' },
      {
        body: outputBody('S3-E-IN-OUT'),
        code: true,
        correct: true,
        feedback: '900.000 supera el tope y queda en 500.000.',
      },
      {
        body: 'Bono con tope: 400000',
        code: true,
        feedback: 'El procedimiento aplica el tope; no resta.',
      },
      { body: 'Bono con tope: ', code: true, feedback: 'v_bono no queda en NULL.' },
    ]),
    explanation:
      'Un parámetro IN OUT entra con el valor de la variable y sale con el que dejó el procedimiento.',
    concept: 'IN OUT',
    review: review('S3-L19'),
    reference: REF.subprograms,
  },
];

const paquetes: BankQuestion[] = [
  {
    key: 'S3-PKG-01',
    level: 'recordar',
    topic: 'paquetes',
    subtopic: 'Especificación y cuerpo',
    type: 'concept',
    response: 'single',
    difficulty: 1,
    prompt: 'En un paquete, ¿qué contiene la especificación?',
    options: textOptions([
      {
        body: 'Lo público: lo que otros pueden usar',
        correct: true,
        feedback: 'El cuerpo contiene la implementación.',
      },
      { body: 'El código de cada subprograma', feedback: 'Eso va en el cuerpo.' },
      { body: 'Solo los elementos privados', feedback: 'Los privados están solo en el cuerpo.' },
      { body: 'Los datos de las tablas', feedback: 'Un paquete guarda código, no filas.' },
    ]),
    explanation:
      'La especificación es el contrato público; el cuerpo, la implementación y lo privado.',
    concept: 'Paquete',
    review: review('S3-L22'),
    reference: REF.packages,
  },
  {
    key: 'S3-PKG-02',
    level: 'aplicar',
    topic: 'paquetes',
    subtopic: 'Uso de un paquete',
    type: 'predict_result',
    response: 'single',
    difficulty: 3,
    prompt:
      'Paula gana 4.200.000 sin bono. aumentar sube el salario un 10 % y lo redondea a miles. ¿Qué escribe la línea «Después»?',
    code: codeOf('S3-E-PAQUETE'),
    options: textOptions([
      { body: 'Después: 50400000', code: true, feedback: 'Ese es el valor antes del aumento.' },
      {
        body: outputOf('S3-E-PAQUETE').find((line) => line.startsWith('Después'))!,
        code: true,
        correct: true,
        feedback: '4.620.000 × 12.',
      },
      { body: 'Después: 4620000', code: true, feedback: 'salario_anual multiplica por 12.' },
      { body: 'Después: 60480000', code: true, feedback: 'Eso sería un aumento del 20 %.' },
    ]),
    explanation:
      'rrhh_pkg.aumentar(7, 10) deja el salario en 4.620.000 y rrhh_pkg.salario_anual(7) devuelve 4.620.000 × 12.',
    concept: 'Paquete',
    review: review('S3-L22'),
    reference: REF.packages,
  },
  {
    key: 'S3-PKG-03',
    level: 'analizar',
    topic: 'paquetes',
    subtopic: 'Elemento privado',
    type: 'find_error',
    response: 'single',
    difficulty: 3,
    prompt: `Oracle no compila el bloque: ${errorOf('S3-E-PAQUETE-PRIVADO')}. ¿Por qué?`,
    code: codeOf('S3-E-PAQUETE-PRIVADO'),
    options: textOptions([
      {
        body: 'redondear solo está en el cuerpo: es privada',
        correct: true,
        feedback: 'Lo que no está en la especificación no se ve fuera.',
      },
      {
        body: 'Falta crear el cuerpo del paquete',
        feedback: 'El cuerpo existe; redondear vive allí.',
      },
      {
        body: 'Los paquetes no tienen funciones',
        feedback: 'Pueden tener funciones y procedimientos.',
      },
      {
        body: 'Hay que llamarla sin el prefijo rrhh_pkg',
        feedback: 'Fuera del paquete el prefijo es obligatorio.',
      },
    ]),
    explanation:
      'Solo lo declarado en la especificación es visible fuera; un elemento solo del cuerpo da PLS-00302 al usarlo desde fuera.',
    concept: 'Elementos privados',
    review: review('S3-L22'),
    reference: REF.packages,
  },
  {
    key: 'S3-PKG-04',
    level: 'analizar',
    topic: 'paquetes',
    subtopic: 'Regla dentro del paquete',
    type: 'interpret_query',
    response: 'single',
    difficulty: 4,
    prompt: `rrhh_pkg.aumentar(7, 20) termina con ${errorOf('S3-E-PAQUETE-TOPE')}. ¿Qué pasa con el salario de Paula?`,
    code: codeOf('S3-E-PAQUETE-TOPE'),
    options: textOptions([
      {
        body: 'No cambia: falla antes del UPDATE',
        correct: true,
        feedback: 'aumentar valida el tope antes de modificar.',
      },
      {
        body: 'Sube un 15 %, el tope permitido',
        feedback: 'El paquete rechaza; no recorta el porcentaje.',
      },
      { body: 'Sube un 20 % y luego avisa', feedback: 'La validación ocurre antes del cambio.' },
      { body: 'Queda en NULL', feedback: 'El salario no se toca.' },
    ]),
    explanation:
      'La regla del tope vive en un solo lugar (el paquete): cualquier programa que lo use la respeta.',
    concept: 'Paquete',
    review: review('S3-L22'),
    reference: REF.packages,
  },
];

const ventas = outputOf('S3-B-TRIGGER-VENTAS');

const triggers: BankQuestion[] = [
  {
    key: 'S3-TRG-01',
    level: 'recordar',
    topic: 'triggers',
    subtopic: ':OLD y :NEW',
    type: 'concept',
    response: 'single',
    difficulty: 1,
    prompt: 'En un trigger de fila sobre un UPDATE, ¿qué contienen :OLD y :NEW?',
    options: textOptions([
      {
        body: ':OLD, la fila antes; :NEW, después',
        correct: true,
        feedback: 'Así se comparan o se auditan los cambios.',
      },
      { body: ':OLD, la fila después; :NEW, antes', feedback: 'Es al revés.' },
      { body: 'Las dos guardan la fila nueva', feedback: ':OLD guarda los valores anteriores.' },
      {
        body: 'Los nombres de las tablas afectadas',
        feedback: 'Guardan valores de columnas de la fila.',
      },
    ]),
    explanation:
      'En un UPDATE, :OLD tiene los valores previos y :NEW los nuevos; en INSERT :OLD es NULL y en DELETE :NEW es NULL.',
    concept: ':OLD y :NEW',
    review: review('S3-L25'),
    reference: REF.triggers,
  },
  {
    key: 'S3-TRG-02',
    level: 'aplicar',
    topic: 'triggers',
    subtopic: 'Sentencia y fila',
    type: 'single_choice',
    response: 'single',
    difficulty: 3,
    prompt:
      'Existen un trigger de sentencia y uno FOR EACH ROW sobre UPDATE OF salario, y cada uno escribe una línea. Ventas tiene cinco personas. ¿Cuántas líneas escribe este UPDATE?',
    code: codeOf('S3-B-TRIGGER-VENTAS'),
    options: textOptions([
      { body: '5', feedback: 'Falta la línea del trigger de sentencia.' },
      { body: String(ventas.length), correct: true, feedback: 'Cinco de fila y una de sentencia.' },
      { body: '2', feedback: 'El de fila se ejecuta una vez por persona.' },
      { body: '10', feedback: 'El de sentencia se ejecuta una sola vez.' },
    ]),
    explanation:
      'FOR EACH ROW se ejecuta por cada fila afectada; el trigger de sentencia, una vez por UPDATE.',
    concept: 'FOR EACH ROW',
    review: review('S3-L24'),
    reference: REF.triggers,
  },
  {
    key: 'S3-TRG-03',
    level: 'aplicar',
    topic: 'triggers',
    subtopic: 'Auditoría',
    type: 'predict_result',
    response: 'single',
    difficulty: 3,
    prompt:
      'Con trg_auditar_salario (AFTER UPDATE OF salario, FOR EACH ROW), se sube 10 % el salario de Paula (4.200.000). ¿Qué queda en AUDITORIA_SALARIOS?',
    code: withSetup('S3-B-AUDIT-PAULA'),
    options: afterOptions(
      {
        example: 'S3-B-AUDIT-PAULA',
        body: 'Una fila: 4.200.000 → 4.620.000.',
        feedback: ':OLD.salario y :NEW.salario de la fila cambiada.',
      },
      1,
      [
        {
          body: 'Una fila con los valores invertidos.',
          rows: [[7, 4620000, 4200000, 'UPDATE']],
          feedback: 'SALARIO_ANTERIOR recibe :OLD, el valor antes del cambio.',
        },
        {
          body: 'Ninguna fila.',
          rows: [],
          feedback: 'El UPDATE de SALARIO dispara el trigger.',
        },
        {
          body: 'Una fila sin salario anterior.',
          rows: [[7, null, 4620000, 'UPDATE']],
          feedback: ':OLD es NULL solo en un INSERT.',
        },
      ],
    ),
    explanation:
      'El trigger inserta una fila por cada fila actualizada con el valor anterior (:OLD) y el nuevo (:NEW).',
    concept: 'Trigger de auditoría',
    review: review('S3-L25'),
    reference: REF.triggers,
  },
  {
    key: 'S3-TRG-04',
    level: 'analizar',
    topic: 'triggers',
    subtopic: 'Elegir BEFORE o AFTER',
    type: 'short_case',
    response: 'single',
    difficulty: 4,
    prompt:
      'Quieres que el nombre se guarde siempre con mayúscula inicial, aunque lo escriban en minúsculas. ¿Qué trigger usas?',
    options: textOptions([
      {
        body: 'BEFORE INSERT FOR EACH ROW: :NEW.nombre := INITCAP(…)',
        correct: true,
        feedback: 'Antes de guardar se puede corregir :NEW.',
      },
      {
        body: 'AFTER INSERT FOR EACH ROW: :NEW.nombre := INITCAP(…)',
        feedback: 'Después del cambio ya no se puede corregir la fila.',
      },
      {
        body: 'AFTER INSERT sin FOR EACH ROW, con UPDATE a la tabla',
        feedback: 'Más trabajo y sin :NEW: un trigger de sentencia no tiene fila.',
      },
      {
        body: 'BEFORE INSERT sin FOR EACH ROW: :NEW.nombre := …',
        feedback: 'Sin FOR EACH ROW no existe :NEW (ORA-04082).',
      },
    ]),
    explanation:
      'Un trigger BEFORE de fila puede modificar los valores que se van a guardar asignando a :NEW.',
    concept: 'BEFORE y AFTER',
    review: review('S3-L24'),
    reference: REF.triggers,
  },
  {
    key: 'S3-TRG-05',
    level: 'analizar',
    topic: 'triggers',
    subtopic: 'Tabla mutante',
    type: 'find_error',
    response: 'single',
    difficulty: 4,
    prompt: `El UPDATE falla con ${errorOf('S3-E-MUTANTE')}. ¿Por qué?`,
    code: withSetup('S3-E-MUTANTE'),
    options: textOptions([
      {
        body: 'El trigger de fila lee la tabla que se modifica',
        correct: true,
        feedback: 'EMPLEADOS está mutando durante el UPDATE.',
      },
      {
        body: 'AVG no se puede usar dentro de un trigger',
        feedback: 'Se puede, fuera de esta situación.',
      },
      {
        body: 'Falta un COMMIT al final del cuerpo del trigger',
        feedback: 'Un trigger no puede hacer COMMIT.',
      },
      {
        body: 'El trigger debería ser BEFORE y no AFTER',
        feedback: 'Un BEFORE de fila tampoco puede leer la tabla mutante.',
      },
    ]),
    explanation:
      'Mientras un UPDATE modifica EMPLEADOS, sus triggers de fila no pueden consultarla: ORA-04091. Es una señal de que esa lógica va en otro lugar.',
    concept: 'Límites de los triggers',
    review: review('S3-L27'),
    reference: REF.triggers,
  },
  {
    key: 'S3-TRG-06',
    level: 'analizar',
    topic: 'triggers',
    subtopic: 'Trigger de validación',
    type: 'interpret_query',
    response: 'single',
    difficulty: 4,
    prompt: `trg_validar_aumento rechaza aumentos de más del 20 %. Este UPDATE termina con ${errorOf('S3-E-TRIGGER-VALIDA')}. ¿Qué salario tiene Valentina después?`,
    code: codeOf('S3-E-TRIGGER-VALIDA'),
    options: textOptions([
      {
        body: String(afterOf('S3-E-TRIGGER-VALIDA').rows[0]?.[2]),
        correct: true,
        feedback: 'El error del trigger deshace la sentencia.',
      },
      { body: '3770000', feedback: 'Ese sería el 30 %: el trigger lo impide.' },
      { body: '3480000', feedback: 'El trigger no recorta al 20 %: rechaza.' },
      { body: 'NULL', feedback: 'El salario no se borra.' },
    ]),
    explanation:
      'Si un trigger lanza un error, la sentencia que lo disparó falla completa y la fila queda como estaba.',
    concept: 'Trigger de validación',
    review: review('S3-L26'),
    reference: REF.triggers,
  },
  {
    key: 'S3-TRG-07',
    level: 'analizar',
    topic: 'triggers',
    subtopic: 'Cuándo usar un trigger',
    type: 'short_case',
    response: 'multiple',
    difficulty: 3,
    prompt: '¿Cuáles son buenos usos de un trigger?',
    options: textOptions([
      {
        body: 'Registrar cada cambio de salario en una auditoría',
        correct: true,
        feedback: 'Automático, local y fácil de seguir.',
      },
      {
        body: 'Rechazar aumentos mayores al 20 % comparando :OLD y :NEW',
        correct: true,
        feedback: 'Una regla de cambio que debe cumplir todo programa.',
      },
      {
        body: 'Calcular la nómina mensual completa ante cualquier cambio',
        feedback: 'Es un proceso: va en un procedimiento.',
      },
      {
        body: 'Confirmar con COMMIT cada inserción',
        feedback: 'Un trigger no puede hacer COMMIT (ORA-04092).',
      },
      {
        body: 'Exigir que el salario sea positivo',
        feedback: 'Una restricción CHECK es más simple y ya existe.',
      },
    ]),
    explanation:
      'Triggers para auditar y para reglas que comparan el antes y el después; procesos en procedimientos y reglas simples en restricciones.',
    concept: 'Límites de los triggers',
    review: review('S3-L27'),
    reference: REF.triggers,
  },
];

export const PLSQL_BANK: readonly OfficialQuestion[] = [
  ...bloques,
  ...variables,
  ...control,
  ...cursores,
  ...excepciones,
  ...subprogramas,
  ...paquetes,
  ...triggers,
].map((question) => finalize(S3, question));
