/** Contratos del dominio de evaluaciones que usa la presentación (la presentación no importa el dominio). */
export {
  ASSESSMENT_TIME_ZONE,
  AUDIENCES,
  CLIENT_EVENT_TYPES,
  EVENT_LABEL,
  EXAM_ONLINE_WINDOW_MS,
  FEEDBACK_LABEL,
  FEEDBACK_MODES,
  formatGrade,
  LIMITS,
  PARTICIPANT_LABEL,
  passes,
  PHASE_LABEL,
  relevantEventCount,
  RELEVANT_EVENTS,
  SUBMITTED_BY_LABEL,
  SUGGESTED_COUNTS,
  type AssessmentPhase,
  type Audience,
  type EventType,
  type FeedbackMode,
  type ParticipantStatus,
  type SelectionMode,
} from '../domain/assessment';
export {
  DIFFICULTIES,
  defaultWeight,
  QUESTION_STATUS_LABEL,
  QUESTION_TYPE_LABEL,
  QUESTION_TYPES,
  RESPONSE_INSTRUCTION,
  RESPONSE_KINDS_BY_TYPE,
  type DataTable,
  type OptionKind,
  type QuestionStatus,
  type QuestionType,
  type ResponseKind,
} from '../domain/question';
export { ASSESSMENT_TOPICS, topicLabel, type AssessmentTopic } from '../domain/topics';
