export const searchGroups = ['Conceptos', 'Lecciones', 'Práctica', 'Recursos'] as const;

export type SearchGroup = (typeof searchGroups)[number];

export interface PublicCatalogEntry {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly group: SearchGroup;
  readonly href: string | null;
  readonly aliases: readonly string[];
  readonly available: boolean;
  readonly navigation?: {
    readonly label: string;
    readonly order: number;
  };
}

/** Catálogo público: no contiene rúbricas, soluciones ni datos administrativos. */
export const publicCatalog: readonly PublicCatalogEntry[] = [
  {
    id: 'home',
    title: 'Inicio',
    description: 'Portada de SQL SELECT LAB y accesos a los recorridos.',
    group: 'Recursos',
    href: '/',
    aliases: ['inicio', 'portada', 'home', 'sql select lab'],
    available: true,
    navigation: { label: 'Inicio', order: 1 },
  },
  {
    id: 'learn',
    title: 'Aprender SELECT',
    description: 'Recorrido de estudio con las nueve lecciones de esta unidad.',
    group: 'Lecciones',
    href: '/learn',
    aliases: ['aprender', 'estudio', 'curso', 'lecciones', 'select'],
    available: true,
    navigation: { label: 'Aprender', order: 2 },
  },
  {
    id: 'presentation',
    title: 'Presentación de la unidad',
    description: 'Exposición guiada por escenas para trabajar con la clase.',
    group: 'Recursos',
    href: '/presentation',
    aliases: ['presentacion', 'exposicion', 'diapositivas', 'escenas', 'clase'],
    available: true,
    navigation: { label: 'Presentación', order: 3 },
  },
  {
    id: 'lab',
    title: 'Laboratorio SQL',
    description: 'Escribe consultas del subconjunto SELECT y revisa su análisis.',
    group: 'Práctica',
    href: '/lab',
    aliases: ['laboratorio', 'lab', 'editor', 'oracle', 'ejecutar consulta'],
    available: true,
    navigation: { label: 'Laboratorio', order: 4 },
  },
  {
    id: 'challenge',
    title: 'SQL Oracle Challenge',
    description: 'Diez misiones para practicar los conceptos de la unidad.',
    group: 'Práctica',
    href: '/challenge',
    aliases: ['challenge', 'quiz', 'juego', 'misiones', 'practica'],
    available: true,
    navigation: { label: 'Challenge', order: 5 },
  },
  {
    id: 'live',
    title: 'Sala en vivo',
    description: 'Entrada por código a una actividad guiada en clase.',
    group: 'Práctica',
    href: '/live',
    aliases: ['en vivo', 'sala', 'codigo', 'qr', 'participar'],
    available: true,
    navigation: { label: 'En vivo', order: 6 },
  },
  {
    id: 'results',
    title: 'Resultados de práctica',
    description: 'Resumen local de puntos, misiones y conceptos por repasar.',
    group: 'Práctica',
    href: '/results',
    aliases: ['resultados', 'progreso', 'puntaje', 'puntuacion', 'repaso'],
    available: true,
    navigation: { label: 'Resultados', order: 7 },
  },
  {
    id: 'resources',
    title: 'Recursos de estudio',
    description: 'Vídeos, chuleta y fuentes académicas de la unidad.',
    group: 'Recursos',
    href: '/resources',
    aliases: ['recursos', 'materiales', 'fuentes', 'chuleta', 'videos'],
    available: true,
    navigation: { label: 'Recursos', order: 8 },
  },
  {
    id: 'lesson-introduction',
    title: 'Introducción a SQL',
    description: 'Distingue tabla, fila y columna antes de consultar datos.',
    group: 'Lecciones',
    href: '/learn/introduccion',
    aliases: ['introduccion', 'sql', 'tabla', 'fila', 'columna', 'l00'],
    available: true,
  },
  {
    id: 'lesson-select',
    title: 'SELECT: qué mostrar',
    description: 'Elige las columnas que aparecerán en el resultado.',
    group: 'Lecciones',
    href: '/learn/select',
    aliases: ['select', 'proyeccion', 'elegir datos', 'l01'],
    available: true,
  },
  {
    id: 'lesson-from',
    title: 'FROM: de dónde vienen los datos',
    description: 'Identifica EMPLEADOS como la tabla de origen.',
    group: 'Lecciones',
    href: '/learn/from',
    aliases: ['from', 'origen', 'tabla empleados', 'l02'],
    available: true,
  },
  {
    id: 'lesson-star',
    title: 'Asterisco: todas las columnas',
    description: 'Comprende qué muestra SELECT * en esta tabla.',
    group: 'Lecciones',
    href: '/learn/asterisco',
    aliases: ['*', 'asterisco', 'select *', 'todas las columnas', 'l03'],
    available: true,
  },
  {
    id: 'lesson-columns',
    title: 'Columnas específicas y orden',
    description: 'Separa columnas con comas y controla el orden de salida.',
    group: 'Lecciones',
    href: '/learn/columnas',
    aliases: ['columnas', 'lista', 'coma', 'orden', 'proyeccion', 'l04'],
    available: true,
  },
  {
    id: 'lesson-expressions',
    title: 'Expresiones y cálculos',
    description: 'Calcula valores con operadores y paréntesis.',
    group: 'Lecciones',
    href: '/learn/expresiones',
    aliases: ['expresiones', 'calculos', 'aritmetica', 'salario anual', 'l05'],
    available: true,
  },
  {
    id: 'lesson-alias',
    title: 'Alias con AS',
    description: 'Cambia la etiqueta de una columna de resultado sin alterar la fuente.',
    group: 'Lecciones',
    href: '/learn/alias',
    aliases: ['as', 'alias', 'encabezado', 'nombre de columna', 'l06'],
    available: true,
  },
  {
    id: 'lesson-distinct',
    title: 'DISTINCT: valores sin repetir',
    description: 'Elimina duplicados de la combinación proyectada.',
    group: 'Lecciones',
    href: '/learn/distinct',
    aliases: ['distinct', 'unicos', 'sin repetir', 'duplicados', 'l07'],
    available: true,
  },
  {
    id: 'lesson-complete-query',
    title: 'Consulta completa de proyección',
    description: 'Integra SELECT, FROM, expresiones y alias en un pedido completo.',
    group: 'Lecciones',
    href: '/learn/consulta-completa',
    aliases: ['consulta completa', 'select from', 'integracion', 'l08'],
    available: true,
  },
  {
    id: 'video-introduction',
    title: 'Vídeo de introducción',
    description: 'Introducción breve a tablas, SELECT y FROM.',
    group: 'Recursos',
    href: '/resources#video-introduccion',
    aliases: ['video', 'videos', 'introduccion', 'v01'],
    available: true,
  },
  {
    id: 'video-summary',
    title: 'Vídeo resumen',
    description: 'Repaso de los conceptos principales de la unidad.',
    group: 'Recursos',
    href: '/resources#video-resumen',
    aliases: ['video', 'videos', 'resumen', 'repaso', 'v02'],
    available: true,
  },
  {
    id: 'future-where',
    title: 'WHERE y comparaciones',
    description: 'Filtrar filas con condiciones pertenece a un módulo futuro.',
    group: 'Conceptos',
    href: null,
    aliases: ['where', 'filtros', 'comparaciones', 'condiciones', 'futuro'],
    available: false,
  },
  {
    id: 'future-between-in',
    title: 'BETWEEN e IN',
    description: 'Rangos y listas de valores pertenecen a un módulo futuro.',
    group: 'Conceptos',
    href: null,
    aliases: ['between', 'in', 'rangos', 'listas', 'futuro'],
    available: false,
  },
  {
    id: 'future-like',
    title: 'LIKE y patrones',
    description: 'La búsqueda de patrones pertenece a un módulo futuro.',
    group: 'Conceptos',
    href: null,
    aliases: ['like', 'patrones', 'comodines', 'futuro'],
    available: false,
  },
  {
    id: 'future-join',
    title: 'JOIN entre tablas',
    description: 'Relacionar varias tablas pertenece a un módulo futuro.',
    group: 'Conceptos',
    href: null,
    aliases: ['join', 'uniones', 'relaciones', 'varias tablas', 'futuro'],
    available: false,
  },
  {
    id: 'future-group-by',
    title: 'GROUP BY y agrupaciones',
    description: 'Agrupar filas pertenece a un módulo futuro.',
    group: 'Conceptos',
    href: null,
    aliases: ['group by', 'group', 'agrupaciones', 'grupos', 'futuro'],
    available: false,
  },
  {
    id: 'future-functions',
    title: 'Funciones SQL',
    description: 'Funciones de texto, fecha y agregación pertenecen a módulos futuros.',
    group: 'Conceptos',
    href: null,
    aliases: ['funciones', 'functions', 'sum', 'count', 'avg', 'futuro'],
    available: false,
  },
] as const;
