import { LESSON_OUTLINE } from '@/features/study/domain/lesson-outline';

export const searchGroups = ['Conceptos', 'Lecciones', 'Práctica', 'Recursos'] as const;

export type SearchGroup = (typeof searchGroups)[number];

export interface PublicCatalogEntry {
  readonly id: string;
  readonly title: string;
  readonly description: string;
  readonly group: SearchGroup;
  readonly href: string | null;
  readonly aliases: readonly string[];
  readonly available: boolean;
  readonly navigation?: {
    readonly label: string;
    readonly order: number;
    /** Rutas adicionales en las que esta entrada figura como activa. */
    readonly alsoActiveOn?: readonly string[];
  };
}

/** Catálogo público: no contiene rúbricas, soluciones ni datos administrativos. */
export const publicCatalog: readonly PublicCatalogEntry[] = [
  {
    id: 'home',
    title: 'Inicio',
    description: 'Portada de SQL SELECT LAB y accesos a los recorridos.',
    group: 'Recursos',
    href: '/',
    aliases: ['inicio', 'portada', 'home', 'sql select lab'],
    available: true,
    navigation: { label: 'Inicio', order: 1 },
  },
  {
    id: 'learn',
    title: 'Modo Estudio',
    description: 'Recorrido de estudio con las nueve lecciones de esta unidad.',
    group: 'Lecciones',
    href: '/learn',
    aliases: ['aprender', 'estudio', 'modo estudio', 'curso', 'lecciones'],
    available: true,
    navigation: { label: 'Aprender', order: 2, alsoActiveOn: ['/presentation'] },
  },
  {
    id: 'presentation',
    title: 'Modo Exposición',
    description: 'Exposición guiada por escenas para trabajar con la clase.',
    group: 'Recursos',
    href: '/presentation',
    aliases: [
      'presentacion',
      'exposicion',
      'modo exposicion',
      'diapositivas',
      'escenas',
      'clase',
      'proyector',
    ],
    available: true,
  },
  {
    id: 'lab',
    title: 'Laboratorio SQL',
    description: 'Escribe consultas del subconjunto SELECT y revisa su análisis.',
    group: 'Práctica',
    href: '/lab',
    aliases: ['laboratorio', 'lab', 'editor', 'oracle', 'ejecutar consulta'],
    available: true,
    navigation: { label: 'Laboratorio', order: 3 },
  },
  {
    id: 'challenge',
    title: 'SQL Oracle Challenge',
    description: 'Diez misiones para practicar los conceptos de la unidad.',
    group: 'Práctica',
    href: '/challenge',
    aliases: ['challenge', 'quiz', 'juego', 'misiones', 'practica'],
    available: true,
    navigation: { label: 'Challenge', order: 4 },
  },
  {
    id: 'live',
    title: 'Sala en vivo',
    description: 'Entrada por código a una actividad guiada en clase.',
    group: 'Práctica',
    href: '/live',
    aliases: ['en vivo', 'sala', 'codigo', 'qr', 'participar'],
    available: true,
    navigation: { label: 'En vivo', order: 5 },
  },
  {
    id: 'results',
    title: 'Resultados de práctica',
    description: 'Resumen local de puntos, misiones y conceptos por repasar.',
    group: 'Práctica',
    href: '/results',
    aliases: ['resultados', 'progreso', 'puntaje', 'puntuacion', 'repaso'],
    available: true,
  },
  {
    id: 'resources',
    title: 'Recursos de estudio',
    description: 'Vídeos, chuleta y fuentes académicas de la unidad.',
    group: 'Recursos',
    href: '/resources',
    aliases: ['recursos', 'materiales', 'fuentes', 'chuleta', 'videos'],
    available: true,
    navigation: { label: 'Recursos', order: 6 },
  },
  ...LESSON_OUTLINE.map((lesson): PublicCatalogEntry => ({
    id: `lesson-${lesson.slug}`,
    title: lesson.title,
    description: lesson.summary,
    group: 'Lecciones',
    href: `/learn/${lesson.slug}`,
    aliases: lesson.keywords,
    available: true,
  })),
  {
    id: 'video-introduction',
    title: 'Vídeo de introducción',
    description: 'Introducción breve a tablas, SELECT y FROM.',
    group: 'Recursos',
    href: '/resources#video-introduccion',
    aliases: ['video', 'videos', 'introduccion', 'v01'],
    available: true,
  },
  {
    id: 'video-summary',
    title: 'Vídeo resumen',
    description: 'Repaso de los conceptos principales de la unidad.',
    group: 'Recursos',
    href: '/resources#video-resumen',
    aliases: ['video', 'videos', 'resumen', 'repaso', 'v02'],
    available: true,
  },
  {
    id: 'concept-select',
    title: 'SELECT',
    description: 'Indica qué columnas o expresiones muestra el resultado.',
    group: 'Conceptos',
    href: '/resources#chuleta-select',
    aliases: ['select', 'seleccionar', 'mostrar', 'proyeccion'],
    available: true,
  },
  {
    id: 'concept-from',
    title: 'FROM',
    description: 'Indica la tabla de la que salen los datos.',
    group: 'Conceptos',
    href: '/resources#chuleta-from',
    aliases: ['from', 'origen', 'tabla'],
    available: true,
  },
  {
    id: 'concept-star',
    title: 'SELECT *',
    description: 'Muestra todas las columnas de la tabla, en su orden.',
    group: 'Conceptos',
    href: '/resources#chuleta-asterisco',
    aliases: ['*', 'select *', 'asterisco', 'todas las columnas'],
    available: true,
  },
  {
    id: 'concept-columns',
    title: 'Lista de columnas',
    description: 'Columnas separadas por coma, en el orden pedido.',
    group: 'Conceptos',
    href: '/resources#chuleta-columnas',
    aliases: ['columnas', 'coma', 'lista', 'orden de columnas'],
    available: true,
  },
  {
    id: 'concept-expressions',
    title: 'Expresiones aritméticas',
    description: 'Cálculos con +, -, *, / y paréntesis sobre columnas numéricas.',
    group: 'Conceptos',
    href: '/resources#chuleta-expresiones',
    aliases: ['expresiones', 'calculos', 'operadores', 'parentesis', 'precedencia'],
    available: true,
  },
  {
    id: 'concept-alias',
    title: 'AS · alias de columna',
    description: 'Da un encabezado claro a una columna del resultado.',
    group: 'Conceptos',
    href: '/resources#chuleta-alias',
    aliases: ['as', 'alias', 'encabezado', 'renombrar columna'],
    available: true,
  },
  {
    id: 'concept-distinct',
    title: 'DISTINCT',
    description: 'Quita las filas repetidas de la proyección completa.',
    group: 'Conceptos',
    href: '/resources#chuleta-distinct',
    aliases: ['distinct', 'unicos', 'sin repetir', 'duplicados'],
    available: true,
  },
  {
    id: 'future-where',
    title: 'WHERE y comparaciones',
    description: 'Filtrar filas con condiciones pertenece a un módulo futuro.',
    group: 'Conceptos',
    href: null,
    aliases: ['where', 'filtros', 'comparaciones', 'condiciones', 'futuro'],
    available: false,
  },
  {
    id: 'future-between-in',
    title: 'BETWEEN e IN',
    description: 'Rangos y listas de valores pertenecen a un módulo futuro.',
    group: 'Conceptos',
    href: null,
    aliases: ['between', 'in', 'rangos', 'listas', 'futuro'],
    available: false,
  },
  {
    id: 'future-like',
    title: 'LIKE y patrones',
    description: 'La búsqueda de patrones pertenece a un módulo futuro.',
    group: 'Conceptos',
    href: null,
    aliases: ['like', 'patrones', 'comodines', 'futuro'],
    available: false,
  },
  {
    id: 'future-join',
    title: 'JOIN entre tablas',
    description: 'Relacionar varias tablas pertenece a un módulo futuro.',
    group: 'Conceptos',
    href: null,
    aliases: ['join', 'uniones', 'relaciones', 'varias tablas', 'futuro'],
    available: false,
  },
  {
    id: 'future-group-by',
    title: 'GROUP BY y agrupaciones',
    description: 'Agrupar filas pertenece a un módulo futuro.',
    group: 'Conceptos',
    href: null,
    aliases: ['group by', 'group', 'agrupaciones', 'grupos', 'futuro'],
    available: false,
  },
  {
    id: 'future-functions',
    title: 'Funciones SQL',
    description: 'Funciones de texto, fecha y agregación pertenecen a módulos futuros.',
    group: 'Conceptos',
    href: null,
    aliases: ['funciones', 'functions', 'sum', 'count', 'avg', 'futuro'],
    available: false,
  },
];
